#!/usr/bin/env python3
"""Encrypter Setup -- single-file, cross-platform installer. Embeds the app,
requirements.txt, and OS-appropriate shortcut/launcher creation, so this one
file is all you need to distribute. Runs on Windows, macOS, and Linux (Debian/
Ubuntu, Fedora/RHEL, Arch, Gentoo, openSUSE, Alpine, and others), detects which
one it's on, and tells the user what it found.

To turn this into a standalone installer executable yourself (PyInstaller does
not cross-compile -- run this on each OS you want a native installer binary for):
    pip install pyinstaller
    pyinstaller --onefile --noconsole --name "Encrypter Setup" installer.py
"""

import platform
import sys

import base64
import os
import queue
import shutil
import subprocess
import threading
import tkinter as tk
from tkinter import filedialog, scrolledtext


# =====================================================================
#  OS / distro detection
# =====================================================================

def detect_system():
    """Identify the current OS (and, on Linux, the distro family) and how to
    get missing packages on it. Returns a dict with at least 'system',
    'pretty' (human-readable name), and 'family'."""
    system = platform.system()
    info = {"system": system, "pretty": system, "family": None, "pkg_cmd": None}

    if system == "Windows":
        build = None
        try:
            build = sys.getwindowsversion().build
        except Exception:
            pass
        if build and build >= 22000:
            info["pretty"] = "Windows 11"
        elif build and build >= 10000:
            info["pretty"] = f"Windows 10 (build {build})"
        else:
            info["pretty"] = f"Windows {platform.release()}".strip()
        info["family"] = "windows"

    elif system == "Darwin":
        ver = platform.mac_ver()[0] or ""
        info["pretty"] = f"macOS {ver}".strip()
        info["family"] = "macos"
        info["pkg_cmd"] = "brew install python-tk"

    elif system == "Linux":
        os_release = {}
        try:
            with open("/etc/os-release", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    k, v = line.split("=", 1)
                    os_release[k] = v.strip().strip('"')
        except OSError:
            pass

        distro_id = os_release.get("ID", "linux").lower()
        id_like = os_release.get("ID_LIKE", "").lower().split()
        info["pretty"] = os_release.get("PRETTY_NAME") or f"Linux ({distro_id})"
        info["distro_id"] = distro_id

        families = [distro_id] + id_like
        if any(f in families for f in ("debian", "ubuntu")):
            info["family"] = "debian"
            info["pkg_cmd"] = "sudo apt install -y python3-tk python3-pip"
        elif any(f in families for f in ("fedora", "rhel", "centos")):
            info["family"] = "fedora"
            info["pkg_cmd"] = "sudo dnf install -y python3-tkinter python3-pip"
        elif "arch" in families:
            info["family"] = "arch"
            info["pkg_cmd"] = "sudo pacman -S --needed tk python-pip"
        elif "gentoo" in families:
            info["family"] = "gentoo"
            info["pkg_cmd"] = "sudo emerge --ask dev-lang/tk dev-python/pip"
        elif any(f in families for f in ("suse", "opensuse")):
            info["family"] = "suse"
            info["pkg_cmd"] = "sudo zypper install -y python3-tk python3-pip"
        elif "alpine" in families:
            info["family"] = "alpine"
            info["pkg_cmd"] = "sudo apk add py3-tkinter py3-pip"
        else:
            info["family"] = "linux-other"
            info["pkg_cmd"] = None
    else:
        info["family"] = "unknown"

    return info


SYSTEM_INFO = detect_system()


ENCRYPTER_PY_B64 = "".join((
    "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiJFbmNyeXB0ZXIgLS0gY3Jvc3MtcGxhdGZvcm0gcGFz"
    "c3dvcmQgdmF1bHQgLyB0ZXh0ICYgZmlsZSBlbmNyeXB0aW9uIHRvb2wuClJ1bnMgb24gV2luZG93"
    "cywgbWFjT1MsIGFuZCBMaW51eC4gUmVxdWlyZXMgUHl0aG9uIDMuOCsgd2l0aCB0a2ludGVyIGFu"
    "ZCB0aGUKYGNyeXB0b2dyYXBoeWAgcGFja2FnZSAoQUVTLTI1Ni1HQ00sIE9wZW5TU0wtYmFja2Vk"
    "LCBpZGVudGljYWwgb24gZXZlcnkgT1MpLgpQYXNzcGhyYXNlIHN0cmluZ3MgY2FuJ3QgYmUgd2lw"
    "ZWQgZnJvbSBtZW1vcnkgKENQeXRob24gc3RyIGltbXV0YWJpbGl0eSkgLS0Ka2V5IG1hdGVyaWFs"
    "IGlzIHJvdXRlZCB0aHJvdWdoIGJ5dGVhcnJheXMgYW5kIGV4cGxpY2l0bHkgemVyb2VkL2xvY2tl"
    "ZCBpbnN0ZWFkLAp3aGljaCBpcyBwb3NzaWJsZSBpbiBQeXRob24gYW5kIGNsb3NlcyBtb3N0IG9m"
    "IHRoZSBnYXAgdmVyc3VzIGEgQysrIGJ1aWxkJ3MKc29kaXVtX21lbXplcm8vbWxvY2suIExvY2tp"
    "bmcgaXMgYmVzdC1lZmZvcnQ6IG9uIExpbnV4IGl0J3MgY29tbW9ubHkgcmVmdXNlZApmb3IgYW4g"
    "dW5wcml2aWxlZ2VkIHByb2Nlc3MgKFJMSU1JVF9NRU1MT0NLKSBhbmQgaXMgc2lsZW50bHkgc2tp"
    "cHBlZCAtLSB0aGUKemVyb2luZyBzdGlsbCBoYXBwZW5zIHJlZ2FyZGxlc3Mgb2Ygd2hldGhlciB0"
    "aGUgbG9jayBzdWNjZWVkZWQuIiIiCgppbXBvcnQgc3lzCgp0cnk6CiAgICBmcm9tIGNyeXB0b2dy"
    "YXBoeS5oYXptYXQucHJpbWl0aXZlcy5jaXBoZXJzLmFlYWQgaW1wb3J0IEFFU0dDTQpleGNlcHQg"
    "SW1wb3J0RXJyb3I6CiAgICBzeXMuZXhpdCgKICAgICAgICAiTWlzc2luZyBkZXBlbmRlbmN5OiAn"
    "Y3J5cHRvZ3JhcGh5Jy5cbiIKICAgICAgICAiSW5zdGFsbCBpdCB3aXRoOlxuICAgICIgKyBzeXMu"
    "ZXhlY3V0YWJsZSArICIgLW0gcGlwIGluc3RhbGwgY3J5cHRvZ3JhcGh5IgogICAgKQoKaW1wb3J0"
    "IGN0eXBlcwppbXBvcnQgb3MKaW1wb3J0IHN0cnVjdAppbXBvcnQganNvbgppbXBvcnQgaGFzaGxp"
    "YgppbXBvcnQgc2VjcmV0cwppbXBvcnQgdGtpbnRlciBhcyB0awpmcm9tIHRraW50ZXIgaW1wb3J0"
    "IHR0aywgZmlsZWRpYWxvZwoKS0VZX0xFTiA9IDMyCklWX0xFTiA9IDEyClRBR19MRU4gPSAxNgpT"
    "QUxUX0xFTiA9IDE2CldSQVBfTEVOID0gU0FMVF9MRU4gKyBJVl9MRU4gKyBUQUdfTEVOICsgS0VZ"
    "X0xFTgoKTUFHSUMgPSBiIlBZRTEiClZBVUxUX01BR0lDID0gYiJQWVYxIgoKQUFEX1RFWFRfQ1RY"
    "ID0gYiJQWUVOQy1URVhULXYxIgpBQURfRklMRV9DVFggPSBiIlBZRU5DLUZJTEUtdjEiCkFBRF9W"
    "QVVMVF9DVFggPSBiIlBZRU5DLVZBVUxULXYxIgpBQURfUk9MRV9QUklNQVJZID0gYiJyb2xlOnBy"
    "aW1hcnkiCkFBRF9ST0xFX1JFQ09WRVJZID0gYiJyb2xlOnJlY292ZXJ5IgoKU0NSWVBUX04gPSAx"
    "IDw8IDE2ClNDUllQVF9SID0gOApTQ1JZUFRfUCA9IDEKU0NSWVBUX01BWE1FTSA9IDE5MiAqIDEw"
    "MjQgKiAxMDI0CgoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyAgTWVtb3J5IGh5Z2llbmU6IHplcm8vbG9jayBi"
    "eXRlYXJyYXlzIGhvbGRpbmcga2V5IG1hdGVyaWFsLgojICBMb2NraW5nIHVzZXMgdGhlIHJpZ2h0"
    "IE9TIGNhbGwgZm9yIHRoZSBjdXJyZW50IHBsYXRmb3JtOyBpZiBpdCdzCiMgIHVuYXZhaWxhYmxl"
    "IG9yIHJlZnVzZWQgKHVucHJpdmlsZWdlZCBwcm9jZXNzKSwgd2Ugc2tpcCBpdCBzaWxlbnRseSAt"
    "LQojICB6ZXJvaW5nIHN0aWxsIGFsd2F5cyBoYXBwZW5zLgojID09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKCmRlZiBf"
    "emVybyhidWY6IGJ5dGVhcnJheSk6CiAgICBpZiBidWY6CiAgICAgICAgY3R5cGVzLm1lbXNldCgo"
    "Y3R5cGVzLmNfY2hhciAqIGxlbihidWYpKS5mcm9tX2J1ZmZlcihidWYpLCAwLCBsZW4oYnVmKSkK"
    "CgppZiBzeXMucGxhdGZvcm0gPT0gIndpbjMyIjoKICAgIF9rZXJuZWwzMiA9IGN0eXBlcy53aW5k"
    "bGwua2VybmVsMzIKCiAgICBkZWYgX2xvY2soYnVmOiBieXRlYXJyYXkpOgogICAgICAgIHRyeToK"
    "ICAgICAgICAgICAgYWRkciA9IGN0eXBlcy5hZGRyZXNzb2YoKGN0eXBlcy5jX2NoYXIgKiBsZW4o"
    "YnVmKSkuZnJvbV9idWZmZXIoYnVmKSkKICAgICAgICAgICAgX2tlcm5lbDMyLlZpcnR1YWxMb2Nr"
    "KGN0eXBlcy5jX3ZvaWRfcChhZGRyKSwgY3R5cGVzLmNfc2l6ZV90KGxlbihidWYpKSkKICAgICAg"
    "ICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICBwYXNzCgogICAgZGVmIF91bmxvY2soYnVm"
    "OiBieXRlYXJyYXkpOgogICAgICAgIHRyeToKICAgICAgICAgICAgYWRkciA9IGN0eXBlcy5hZGRy"
    "ZXNzb2YoKGN0eXBlcy5jX2NoYXIgKiBsZW4oYnVmKSkuZnJvbV9idWZmZXIoYnVmKSkKICAgICAg"
    "ICAgICAgX2tlcm5lbDMyLlZpcnR1YWxVbmxvY2soY3R5cGVzLmNfdm9pZF9wKGFkZHIpLCBjdHlw"
    "ZXMuY19zaXplX3QobGVuKGJ1ZikpKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAg"
    "ICAgIHBhc3MKCmVsc2U6CiAgICB0cnk6CiAgICAgICAgX2xpYmMgPSBjdHlwZXMuQ0RMTCgibGli"
    "Yy5zby42IiBpZiBzeXMucGxhdGZvcm0uc3RhcnRzd2l0aCgibGludXgiKSBlbHNlIE5vbmUsIHVz"
    "ZV9lcnJubz1UcnVlKQogICAgZXhjZXB0IE9TRXJyb3I6CiAgICAgICAgX2xpYmMgPSBOb25lCgog"
    "ICAgZGVmIF9sb2NrKGJ1ZjogYnl0ZWFycmF5KToKICAgICAgICBpZiBub3QgX2xpYmM6CiAgICAg"
    "ICAgICAgIHJldHVybgogICAgICAgIHRyeToKICAgICAgICAgICAgYWRkciA9IGN0eXBlcy5hZGRy"
    "ZXNzb2YoKGN0eXBlcy5jX2NoYXIgKiBsZW4oYnVmKSkuZnJvbV9idWZmZXIoYnVmKSkKICAgICAg"
    "ICAgICAgX2xpYmMubWxvY2soY3R5cGVzLmNfdm9pZF9wKGFkZHIpLCBjdHlwZXMuY19zaXplX3Qo"
    "bGVuKGJ1ZikpKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MgICMg"
    "Y29tbW9ubHkgcmVmdXNlZCBmb3IgYW4gdW5wcml2aWxlZ2VkIHByb2Nlc3MgKFJMSU1JVF9NRU1M"
    "T0NLKQoKICAgIGRlZiBfdW5sb2NrKGJ1ZjogYnl0ZWFycmF5KToKICAgICAgICBpZiBub3QgX2xp"
    "YmM6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIHRyeToKICAgICAgICAgICAgYWRkciA9IGN0"
    "eXBlcy5hZGRyZXNzb2YoKGN0eXBlcy5jX2NoYXIgKiBsZW4oYnVmKSkuZnJvbV9idWZmZXIoYnVm"
    "KSkKICAgICAgICAgICAgX2xpYmMubXVubG9jayhjdHlwZXMuY192b2lkX3AoYWRkciksIGN0eXBl"
    "cy5jX3NpemVfdChsZW4oYnVmKSkpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAg"
    "ICAgcGFzcwoKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09CiMgIEFFUy0yNTYtR0NNIHZpYSB0aGUgYGNyeXB0b2dy"
    "YXBoeWAgcGFja2FnZSAoT3BlblNTTC1iYWNrZWQsIGlkZW50aWNhbAojICBvbiBXaW5kb3dzL21h"
    "Y09TL0xpbnV4KS4gS2VwdCB0aGUgZXhhY3Qgc2FtZSBmdW5jdGlvbiBzaWduYXR1cmVzIGFzIHRo"
    "ZQojICBvcmlnaW5hbCBXaW5kb3dzLUNORyBpbXBsZW1lbnRhdGlvbiBzbyBub3RoaW5nIGVsc2Ug"
    "aW4gdGhpcyBmaWxlIGNoYW5nZXMuCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpjbGFzcyBCQ3J5cHRFcnJvcihF"
    "eGNlcHRpb24pOgogICAgIiIiR2VuZXJpYyBjcnlwdG8tb3BlcmF0aW9uIGVycm9yLiBOYW1lIGtl"
    "cHQgYXMtaXMgKHJhdGhlciB0aGFuIHJlbmFtZWQpCiAgICBzbyB0aGUgbWFueSBjYWxsIHNpdGVz"
    "IGVsc2V3aGVyZSBpbiB0aGlzIGZpbGUgdGhhdCBjYXRjaCBpdCBkb24ndCBuZWVkCiAgICB0byBj"
    "aGFuZ2UuIiIiCiAgICBwYXNzCgoKZGVmIGFlc19nY21fZW5jcnlwdChrZXksIG5vbmNlLCBwbGFp"
    "bnRleHQsIGFhZDogYnl0ZXMgPSBiIiIpOgogICAgY29tYmluZWQgPSBBRVNHQ00oYnl0ZXMoa2V5"
    "KSkuZW5jcnlwdChieXRlcyhub25jZSksIGJ5dGVzKHBsYWludGV4dCksIGFhZCBpZiBhYWQgZWxz"
    "ZSBOb25lKQogICAgcmV0dXJuIGNvbWJpbmVkWzotVEFHX0xFTl0sIGNvbWJpbmVkWy1UQUdfTEVO"
    "Ol0KCgpkZWYgYWVzX2djbV9kZWNyeXB0KGtleSwgbm9uY2UsIGNpcGhlcnRleHQsIHRhZywgYWFk"
    "OiBieXRlcyA9IGIiIikgLT4gYnl0ZWFycmF5OgogICAgdHJ5OgogICAgICAgIHBsYWludGV4dCA9"
    "IEFFU0dDTShieXRlcyhrZXkpKS5kZWNyeXB0KGJ5dGVzKG5vbmNlKSwgYnl0ZXMoY2lwaGVydGV4"
    "dCkgKyBieXRlcyh0YWcpLCBhYWQgaWYgYWFkIGVsc2UgTm9uZSkKICAgIGV4Y2VwdCBFeGNlcHRp"
    "b24gYXMgZToKICAgICAgICByYWlzZSBCQ3J5cHRFcnJvcihmImRlY3J5cHQgZmFpbGVkIChhdXRo"
    "ZW50aWNhdGlvbiBmYWlsZWQpOiB7ZX0iKQogICAgcmV0dXJuIGJ5dGVhcnJheShwbGFpbnRleHQp"
    "CgoKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09CiMgIEtleSBkZXJpdmF0aW9uICsga2V5LXdyYXAgKG1pcnJvcnMg"
    "dGhlIEMrKyBLZXlXcmFwIGxheW91dDogc2FsdHxub25jZXx0YWd8ZW5jX2tleSkKIyA9PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT0KCmRlZiBkZXJpdmVfa2V5KHBhc3NwaHJhc2U6IHN0ciwgc2FsdDogYnl0ZXMpIC0+IGJ5"
    "dGVhcnJheToKICAgIHJhdyA9IGhhc2hsaWIuc2NyeXB0KHBhc3NwaHJhc2UuZW5jb2RlKCJ1dGYt"
    "OCIpLCBzYWx0PXNhbHQsIG49U0NSWVBUX04sIHI9U0NSWVBUX1IsIHA9U0NSWVBUX1AsIG1heG1l"
    "bT1TQ1JZUFRfTUFYTUVNLCBka2xlbj1LRVlfTEVOKQogICAga2V5ID0gYnl0ZWFycmF5KHJhdykK"
    "ICAgIF9sb2NrKGtleSkKICAgIHJldHVybiBrZXkKCgpjbGFzcyBLZXlXcmFwOgogICAgX19zbG90"
    "c19fID0gKCJzYWx0IiwgIm5vbmNlIiwgInRhZyIsICJlbmNfa2V5IikKCiAgICBkZWYgX19pbml0"
    "X18oc2VsZiwgc2FsdCwgbm9uY2UsIHRhZywgZW5jX2tleSk6CiAgICAgICAgc2VsZi5zYWx0LCBz"
    "ZWxmLm5vbmNlLCBzZWxmLnRhZywgc2VsZi5lbmNfa2V5ID0gc2FsdCwgbm9uY2UsIHRhZywgZW5j"
    "X2tleQoKCmRlZiB3cmFwX2tleShwYXNzcGhyYXNlOiBzdHIsIGRlaywgcm9sZV9hYWQ6IGJ5dGVz"
    "KSAtPiBLZXlXcmFwOgogICAgc2FsdCA9IHNlY3JldHMudG9rZW5fYnl0ZXMoU0FMVF9MRU4pCiAg"
    "ICBub25jZSA9IHNlY3JldHMudG9rZW5fYnl0ZXMoSVZfTEVOKQogICAga2VrID0gZGVyaXZlX2tl"
    "eShwYXNzcGhyYXNlLCBzYWx0KQogICAgdHJ5OgogICAgICAgIGVuY19rZXksIHRhZyA9IGFlc19n"
    "Y21fZW5jcnlwdChrZWssIG5vbmNlLCBkZWssIHJvbGVfYWFkKQogICAgZmluYWxseToKICAgICAg"
    "ICBfemVybyhrZWspCiAgICAgICAgX3VubG9jayhrZWspCiAgICByZXR1cm4gS2V5V3JhcChzYWx0"
    "LCBub25jZSwgdGFnLCBlbmNfa2V5KQoKCmRlZiB1bndyYXBfa2V5KHBhc3NwaHJhc2U6IHN0ciwg"
    "d3JhcDogS2V5V3JhcCwgcm9sZV9hYWQ6IGJ5dGVzKSAtPiBieXRlYXJyYXk6CiAgICBrZWsgPSBk"
    "ZXJpdmVfa2V5KHBhc3NwaHJhc2UsIHdyYXAuc2FsdCkKICAgIHRyeToKICAgICAgICBkZWsgPSBh"
    "ZXNfZ2NtX2RlY3J5cHQoa2VrLCB3cmFwLm5vbmNlLCB3cmFwLmVuY19rZXksIHdyYXAudGFnLCBy"
    "b2xlX2FhZCkKICAgIGZpbmFsbHk6CiAgICAgICAgX3plcm8oa2VrKQogICAgICAgIF91bmxvY2so"
    "a2VrKQogICAgX2xvY2soZGVrKQogICAgcmV0dXJuIGRlawoKCmRlZiB3cmFwX3RvX2J5dGVzKHc6"
    "IEtleVdyYXApIC0+IGJ5dGVzOgogICAgcmV0dXJuIHcuc2FsdCArIHcubm9uY2UgKyB3LnRhZyAr"
    "IHcuZW5jX2tleQoKCmRlZiB3cmFwX2Zyb21fYnl0ZXMoYjogYnl0ZXMpIC0+IEtleVdyYXA6CiAg"
    "ICBwID0gMAogICAgc2FsdCA9IGJbcDpwICsgU0FMVF9MRU5dOyBwICs9IFNBTFRfTEVOCiAgICBu"
    "b25jZSA9IGJbcDpwICsgSVZfTEVOXTsgcCArPSBJVl9MRU4KICAgIHRhZyA9IGJbcDpwICsgVEFH"
    "X0xFTl07IHAgKz0gVEFHX0xFTgogICAgZW5jX2tleSA9IGJbcDpwICsgS0VZX0xFTl0KICAgIHJl"
    "dHVybiBLZXlXcmFwKHNhbHQsIG5vbmNlLCB0YWcsIGVuY19rZXkpCgoKZGVmIHRvX2hleChiOiBi"
    "eXRlcykgLT4gc3RyOgogICAgcmV0dXJuIGIuaGV4KCkKCgpkZWYgZnJvbV9oZXgoczogc3RyKSAt"
    "PiBieXRlczoKICAgIHJldHVybiBieXRlcy5mcm9taGV4KHMuc3RyaXAoKSkKCgpkZWYgZ2VuZXJh"
    "dGVfcGFzc3BocmFzZShudW1fZ3JvdXBzPTYsIGdyb3VwX3NpemU9NCkgLT4gc3RyOgogICAgY2hh"
    "cnNldCA9ICJBQkNERUZHSEpLTE1OUFFSU1RVVldYWVoiICJhYmNkZWZnaGlqa21ucHFyc3R1dnd4"
    "eXoiICIyMzQ1Njc4OSIKICAgIGdyb3VwcyA9IFsiIi5qb2luKHNlY3JldHMuY2hvaWNlKGNoYXJz"
    "ZXQpIGZvciBfIGluIHJhbmdlKGdyb3VwX3NpemUpKSBmb3IgXyBpbiByYW5nZShudW1fZ3JvdXBz"
    "KV0KICAgIHJldHVybiAiLSIuam9pbihncm91cHMpCgoKZGVmIGdlbmVyYXRlX3NpdGVfcGFzc3dv"
    "cmQobGVuZ3RoPTIwKSAtPiBzdHI6CiAgICBjaGFyc2V0ID0gIkFCQ0RFRkdISktMTU5QUVJTVFVW"
    "V1hZWiIgImFiY2RlZmdoaWprbW5wcXJzdHV2d3h5eiIgIjIzNDU2Nzg5IiAiIUAjJCVeJiooKS1f"
    "PStbXXt9IgogICAgcmV0dXJuICIiLmpvaW4oc2VjcmV0cy5jaG9pY2UoY2hhcnNldCkgZm9yIF8g"
    "aW4gcmFuZ2UobGVuZ3RoKSkKCgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQojICBEYXJrIHRoZW1lCiMgPT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09CgpBQ0NFTlRfQ09MT1IgPSAiIzEyMTMxOCIKQUNDRU5UX1NVQlRFWFQgPSAiIzhjOTRh"
    "OCIKQk9EWV9DT0xPUiA9ICIjMWMxZTI0IgpFRElUX0JHX0NPTE9SID0gIiMxNDE2MWIiClRFWFRf"
    "Q09MT1IgPSAiI2U2ZThlZCIKQk9SREVSX0NPTE9SID0gIiMzYzQwNGEiCkJUTl9CRyA9ICIjMmEy"
    "ZDM2IgpCVE5fQkdfSE9WRVIgPSAiIzM4M2M0OCIKQlROX0JHX1BSRVNTRUQgPSAiIzFlMjAyNyIK"
    "QlROX1BSSU1BUllfQkcgPSAiIzRhNjZkNiIKQlROX1BSSU1BUllfQkdfSE9WRVIgPSAiIzVjNzhl"
    "NiIKQlROX1BSSU1BUllfQkdfUFJFU1NFRCA9ICIjM2E1NGIyIgpFUlJPUl9URVhUID0gIiNmZjgw"
    "ODAiCgpGT05UX05PUk1BTCA9ICgiU2Vnb2UgVUkiLCAxMCkKRk9OVF9USVRMRSA9ICgiU2Vnb2Ug"
    "VUkiLCAyMCwgImJvbGQiKQpGT05UX1NVQlRJVExFID0gKCJTZWdvZSBVSSIsIDkpCgpNQVJHSU4g"
    "PSAxOAoKCmRlZiBoZXhfdG9fcmdiKGNvbG9yKToKICAgIGNvbG9yID0gY29sb3IubHN0cmlwKCIj"
    "IikKICAgIHJldHVybiB0dXBsZShpbnQoY29sb3JbaTppICsgMl0sIDE2KSBmb3IgaSBpbiAoMCwg"
    "MiwgNCkpCgoKZGVmIHJnYl90b19oZXgociwgZywgYik6CiAgICByZXR1cm4gZiIje3I6MDJ4fXtn"
    "OjAyeH17YjowMnh9IgoKCmRlZiBhZGp1c3RfYnJpZ2h0bmVzcyhjb2xvciwgZGVsdGEpOgogICAg"
    "ciwgZywgYiA9IGhleF90b19yZ2IoY29sb3IpCiAgICByID0gbWF4KDAsIG1pbigyNTUsIHIgKyBk"
    "ZWx0YSkpCiAgICBnID0gbWF4KDAsIG1pbigyNTUsIGcgKyBkZWx0YSkpCiAgICBiID0gbWF4KDAs"
    "IG1pbigyNTUsIGIgKyBkZWx0YSkpCiAgICByZXR1cm4gcmdiX3RvX2hleChyLCBnLCBiKQoKCmRl"
    "ZiBkcmF3X3ZlcnRpY2FsX2dyYWRpZW50KGNhbnZhcywgeDEsIHkxLCB4MiwgeTIsIGNvbG9yX3Rv"
    "cCwgY29sb3JfYm90dG9tKToKICAgIHIxLCBnMSwgYjEgPSBoZXhfdG9fcmdiKGNvbG9yX3RvcCkK"
    "ICAgIHIyLCBnMiwgYjIgPSBoZXhfdG9fcmdiKGNvbG9yX2JvdHRvbSkKICAgIGhlaWdodCA9IGlu"
    "dCh5MiAtIHkxKQogICAgaWYgaGVpZ2h0IDw9IDA6CiAgICAgICAgcmV0dXJuCiAgICBmb3IgaSBp"
    "biByYW5nZShoZWlnaHQpOgogICAgICAgIHQgPSBpIC8gbWF4KGhlaWdodCAtIDEsIDEpCiAgICAg"
    "ICAgciA9IGludChyMSArIChyMiAtIHIxKSAqIHQpCiAgICAgICAgZyA9IGludChnMSArIChnMiAt"
    "IGcxKSAqIHQpCiAgICAgICAgYiA9IGludChiMSArIChiMiAtIGIxKSAqIHQpCiAgICAgICAgY2Fu"
    "dmFzLmNyZWF0ZV9saW5lKHgxLCB5MSArIGksIHgyLCB5MSArIGksIGZpbGw9cmdiX3RvX2hleChy"
    "LCBnLCBiKSkKCgpkZWYgcm91bmRlZF9yZWN0X3BvaW50cyh4MSwgeTEsIHgyLCB5Miwgcik6CiAg"
    "ICByID0gbWluKHIsICh4MiAtIHgxKSAvIDIsICh5MiAtIHkxKSAvIDIpCiAgICByZXR1cm4gWwog"
    "ICAgICAgIHgxICsgciwgeTEsIHgyIC0gciwgeTEsIHgyLCB5MSwgeDIsIHkxICsgciwKICAgICAg"
    "ICB4MiwgeTIgLSByLCB4MiwgeTIsIHgyIC0gciwgeTIsIHgxICsgciwgeTIsCiAgICAgICAgeDEs"
    "IHkyLCB4MSwgeTIgLSByLCB4MSwgeTEgKyByLCB4MSwgeTEsCiAgICBdCgoKZGVmIGRyYXdfcm91"
    "bmRlZF9yZWN0KGNhbnZhcywgeDEsIHkxLCB4MiwgeTIsIHI9OCwgKiprd2FyZ3MpOgogICAgcmV0"
    "dXJuIGNhbnZhcy5jcmVhdGVfcG9seWdvbihyb3VuZGVkX3JlY3RfcG9pbnRzKHgxLCB5MSwgeDIs"
    "IHkyLCByKSwgc21vb3RoPVRydWUsICoqa3dhcmdzKQoKCmRlZiBhcHBseV9kYXJrX3RpdGxlYmFy"
    "KHdpbmRvdyk6CiAgICAiIiJXaW5kb3dzLW9ubHkgY29zbWV0aWMgdG91Y2ggKGRhcmsgdGl0bGVi"
    "YXIgdmlhIERXTSkuIE5vLW9wIGVsc2V3aGVyZSAtLQogICAgbWFjT1MgZm9sbG93cyB0aGUgc3lz"
    "dGVtIGxpZ2h0L2RhcmsgYXBwZWFyYW5jZSBhdXRvbWF0aWNhbGx5LCBhbmQgbW9zdAogICAgTGlu"
    "dXggd2luZG93IG1hbmFnZXJzIGRvbid0IGV4cG9zZSBhbiBlcXVpdmFsZW50IHBlci13aW5kb3cg"
    "QVBJLiIiIgogICAgaWYgc3lzLnBsYXRmb3JtICE9ICJ3aW4zMiI6CiAgICAgICAgcmV0dXJuCiAg"
    "ICB0cnk6CiAgICAgICAgd2luZG93LnVwZGF0ZV9pZGxldGFza3MoKQogICAgICAgIGh3bmQgPSBj"
    "dHlwZXMud2luZGxsLnVzZXIzMi5HZXRQYXJlbnQod2luZG93LndpbmZvX2lkKCkpCiAgICAgICAg"
    "ZHdtYXBpID0gY3R5cGVzLndpbmRsbC5kd21hcGkKICAgICAgICB2YWx1ZSA9IGN0eXBlcy5jX2lu"
    "dCgxKQogICAgICAgIGZvciBhdHRyIGluICgyMCwgMTkpOgogICAgICAgICAgICBociA9IGR3bWFw"
    "aS5Ed21TZXRXaW5kb3dBdHRyaWJ1dGUoaHduZCwgYXR0ciwgY3R5cGVzLmJ5cmVmKHZhbHVlKSwg"
    "Y3R5cGVzLnNpemVvZih2YWx1ZSkpCiAgICAgICAgICAgIGlmIGhyID09IDA6CiAgICAgICAgICAg"
    "ICAgICBicmVhawogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBwYXNzCgoKZGVmIGNlbnRl"
    "cl93aW5kb3cod2luLCBwYXJlbnQsIHdpZHRoLCBoZWlnaHQpOgogICAgd2luLnVwZGF0ZV9pZGxl"
    "dGFza3MoKQogICAgaWYgcGFyZW50IGlzIG5vdCBOb25lIGFuZCBwYXJlbnQud2luZm9fZXhpc3Rz"
    "KCk6CiAgICAgICAgcHgsIHB5ID0gcGFyZW50LndpbmZvX3Jvb3R4KCksIHBhcmVudC53aW5mb19y"
    "b290eSgpCiAgICAgICAgcHcsIHBoID0gcGFyZW50LndpbmZvX3dpZHRoKCksIHBhcmVudC53aW5m"
    "b19oZWlnaHQoKQogICAgZWxzZToKICAgICAgICBweCwgcHkgPSAwLCAwCiAgICAgICAgcHcsIHBo"
    "ID0gd2luLndpbmZvX3NjcmVlbndpZHRoKCksIHdpbi53aW5mb19zY3JlZW5oZWlnaHQoKQogICAg"
    "eCA9IHB4ICsgKHB3IC0gd2lkdGgpIC8vIDIKICAgIHkgPSBweSArIChwaCAtIGhlaWdodCkgLy8g"
    "MgogICAgd2luLmdlb21ldHJ5KGYie3dpZHRofXh7aGVpZ2h0fSt7eH0re3l9IikKCgpjbGFzcyBS"
    "b3VuZGVkQnV0dG9uKHRrLkNhbnZhcyk6CiAgICBkZWYgX19pbml0X18oc2VsZiwgcGFyZW50LCB0"
    "ZXh0LCBjb21tYW5kPU5vbmUsIHdpZHRoPTIwMCwgaGVpZ2h0PTQwLCBwcmltYXJ5PUZhbHNlLCBy"
    "YWRpdXM9OCwgZm9udD1Ob25lLCBiZz1CT0RZX0NPTE9SKToKICAgICAgICBzdXBlcigpLl9faW5p"
    "dF9fKHBhcmVudCwgd2lkdGg9d2lkdGgsIGhlaWdodD1oZWlnaHQsIGJnPWJnLCBoaWdobGlnaHR0"
    "aGlja25lc3M9MCwgYmQ9MCwgY3Vyc29yPSJoYW5kMiIpCiAgICAgICAgc2VsZi5jb21tYW5kID0g"
    "Y29tbWFuZAogICAgICAgIHNlbGYucHJpbWFyeSA9IHByaW1hcnkKICAgICAgICBzZWxmLnJhZGl1"
    "cyA9IHJhZGl1cwogICAgICAgIHNlbGYudGV4dCA9IHRleHQKICAgICAgICBzZWxmLmZvbnQgPSBm"
    "b250IG9yIEZPTlRfTk9STUFMCiAgICAgICAgc2VsZi53ID0gd2lkdGgKICAgICAgICBzZWxmLmgg"
    "PSBoZWlnaHQKICAgICAgICBzZWxmLl9zdGF0ZSA9ICJpZGxlIgogICAgICAgIHNlbGYuX2RyYXco"
    "KQogICAgICAgIHNlbGYuYmluZCgiPEVudGVyPiIsIHNlbGYuX29uX2VudGVyKQogICAgICAgIHNl"
    "bGYuYmluZCgiPExlYXZlPiIsIHNlbGYuX29uX2xlYXZlKQogICAgICAgIHNlbGYuYmluZCgiPEJ1"
    "dHRvblByZXNzLTE+Iiwgc2VsZi5fb25fcHJlc3MpCiAgICAgICAgc2VsZi5iaW5kKCI8QnV0dG9u"
    "UmVsZWFzZS0xPiIsIHNlbGYuX29uX3JlbGVhc2UpCgogICAgZGVmIF9jb2xvcnMoc2VsZik6CiAg"
    "ICAgICAgaWYgc2VsZi5wcmltYXJ5OgogICAgICAgICAgICByZXR1cm4geyJpZGxlIjogQlROX1BS"
    "SU1BUllfQkcsICJob3ZlciI6IEJUTl9QUklNQVJZX0JHX0hPVkVSLCAicHJlc3NlZCI6IEJUTl9Q"
    "UklNQVJZX0JHX1BSRVNTRUR9CiAgICAgICAgcmV0dXJuIHsiaWRsZSI6IEJUTl9CRywgImhvdmVy"
    "IjogQlROX0JHX0hPVkVSLCAicHJlc3NlZCI6IEJUTl9CR19QUkVTU0VEfQoKICAgIGRlZiBfZHJh"
    "dyhzZWxmKToKICAgICAgICBzZWxmLmRlbGV0ZSgiYWxsIikKICAgICAgICBjb2xvciA9IHNlbGYu"
    "X2NvbG9ycygpW3NlbGYuX3N0YXRlXQogICAgICAgIGJvcmRlciA9IGNvbG9yIGlmIHNlbGYucHJp"
    "bWFyeSBlbHNlIEJPUkRFUl9DT0xPUgogICAgICAgIGRyYXdfcm91bmRlZF9yZWN0KHNlbGYsIDEs"
    "IDEsIHNlbGYudyAtIDEsIHNlbGYuaCAtIDEsIHNlbGYucmFkaXVzLCBmaWxsPWNvbG9yLCBvdXRs"
    "aW5lPWJvcmRlcikKICAgICAgICBmZyA9ICIjZmZmZmZmIiBpZiBzZWxmLnByaW1hcnkgZWxzZSBU"
    "RVhUX0NPTE9SCiAgICAgICAgc2VsZi5jcmVhdGVfdGV4dChzZWxmLncgLy8gMiwgc2VsZi5oIC8v"
    "IDIsIHRleHQ9c2VsZi50ZXh0LCBmaWxsPWZnLCBmb250PXNlbGYuZm9udCkKCiAgICBkZWYgX29u"
    "X2VudGVyKHNlbGYsIF9lKToKICAgICAgICBpZiBzZWxmLl9zdGF0ZSAhPSAicHJlc3NlZCI6CiAg"
    "ICAgICAgICAgIHNlbGYuX3N0YXRlID0gImhvdmVyIgogICAgICAgICAgICBzZWxmLl9kcmF3KCkK"
    "CiAgICBkZWYgX29uX2xlYXZlKHNlbGYsIF9lKToKICAgICAgICBzZWxmLl9zdGF0ZSA9ICJpZGxl"
    "IgogICAgICAgIHNlbGYuX2RyYXcoKQoKICAgIGRlZiBfb25fcHJlc3Moc2VsZiwgX2UpOgogICAg"
    "ICAgIHNlbGYuX3N0YXRlID0gInByZXNzZWQiCiAgICAgICAgc2VsZi5fZHJhdygpCgogICAgZGVm"
    "IF9vbl9yZWxlYXNlKHNlbGYsIGUpOgogICAgICAgIGluc2lkZSA9IDAgPD0gZS54IDw9IHNlbGYu"
    "dyBhbmQgMCA8PSBlLnkgPD0gc2VsZi5oCiAgICAgICAgc2VsZi5fc3RhdGUgPSAiaG92ZXIiIGlm"
    "IGluc2lkZSBlbHNlICJpZGxlIgogICAgICAgIHNlbGYuX2RyYXcoKQogICAgICAgIGlmIGluc2lk"
    "ZSBhbmQgc2VsZi5jb21tYW5kOgogICAgICAgICAgICBzZWxmLmNvbW1hbmQoKQoKCiMgPT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09CiMgIERpYWxvZ3MKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KCmRlZiBzaG93X21lc3NhZ2UocGFyZW50"
    "LCB0aXRsZSwgbWVzc2FnZSwgaXNfZXJyb3I9RmFsc2UpOgogICAgd2luID0gdGsuVG9wbGV2ZWwo"
    "cGFyZW50KQogICAgd2luLnRpdGxlKHRpdGxlKQogICAgd2luLmNvbmZpZ3VyZShiZz1CT0RZX0NP"
    "TE9SKQogICAgd2luLnJlc2l6YWJsZShGYWxzZSwgRmFsc2UpCiAgICB3aW4udHJhbnNpZW50KHBh"
    "cmVudCkKICAgIHdpZHRoLCBoZWlnaHQgPSA0MjAsIDE3MAogICAgYXBwbHlfZGFya190aXRsZWJh"
    "cih3aW4pCgogICAgZmcgPSBFUlJPUl9URVhUIGlmIGlzX2Vycm9yIGVsc2UgVEVYVF9DT0xPUgog"
    "ICAgdGsuTGFiZWwod2luLCB0ZXh0PW1lc3NhZ2UsIGJnPUJPRFlfQ09MT1IsIGZnPWZnLCBmb250"
    "PUZPTlRfTk9STUFMLCBqdXN0aWZ5PSJsZWZ0IiwKICAgICAgICAgICAgIHdyYXBsZW5ndGg9d2lk"
    "dGggLSAyICogTUFSR0lOLCBhbmNob3I9InciKS5wYWNrKHBhZHg9TUFSR0lOLCBwYWR5PShNQVJH"
    "SU4sIDEwKSwgZmlsbD0iYm90aCIsIGV4cGFuZD1UcnVlKQoKICAgIGJ0bl9mcmFtZSA9IHRrLkZy"
    "YW1lKHdpbiwgYmc9Qk9EWV9DT0xPUikKICAgIGJ0bl9mcmFtZS5wYWNrKHBhZHk9KDAsIE1BUkdJ"
    "TikpCiAgICBSb3VuZGVkQnV0dG9uKGJ0bl9mcmFtZSwgIk9LIiwgY29tbWFuZD13aW4uZGVzdHJv"
    "eSwgd2lkdGg9MTAwLCBoZWlnaHQ9MzIsIHByaW1hcnk9VHJ1ZSkucGFjaygpCgogICAgd2luLnBy"
    "b3RvY29sKCJXTV9ERUxFVEVfV0lORE9XIiwgd2luLmRlc3Ryb3kpCiAgICB3aW4uYmluZCgiPFJl"
    "dHVybj4iLCBsYW1iZGEgZTogd2luLmRlc3Ryb3koKSkKICAgIHdpbi5iaW5kKCI8RXNjYXBlPiIs"
    "IGxhbWJkYSBlOiB3aW4uZGVzdHJveSgpKQogICAgY2VudGVyX3dpbmRvdyh3aW4sIHBhcmVudCwg"
    "d2lkdGgsIGhlaWdodCkKICAgIHdpbi5ncmFiX3NldCgpCiAgICB3aW4ud2FpdF93aW5kb3coKQoK"
    "CmRlZiBzaG93X2lucHV0X2RpYWxvZyhwYXJlbnQsIHRpdGxlLCBwcm9tcHQsIG1hc2tlZD1GYWxz"
    "ZSwgbXVsdGlsaW5lPUZhbHNlLCBkZWZhdWx0PSIiLCByZWFkX29ubHk9RmFsc2UpOgogICAgcmVz"
    "dWx0ID0geyJvayI6IEZhbHNlLCAidmFsdWUiOiAiIn0KICAgIHdpbiA9IHRrLlRvcGxldmVsKHBh"
    "cmVudCkKICAgIHdpbi50aXRsZSh0aXRsZSkKICAgIHdpbi5jb25maWd1cmUoYmc9Qk9EWV9DT0xP"
    "UikKICAgIHdpbi5yZXNpemFibGUoRmFsc2UsIEZhbHNlKQogICAgd2luLnRyYW5zaWVudChwYXJl"
    "bnQpCiAgICB3aWR0aCA9IDQ4MAogICAgaGVpZ2h0ID0gKDIzMCBpZiBtdWx0aWxpbmUgZWxzZSAx"
    "MzApICsgKDAgaWYgbm90IHJlYWRfb25seSBlbHNlIDgpCiAgICBhcHBseV9kYXJrX3RpdGxlYmFy"
    "KHdpbikKCiAgICB0ay5MYWJlbCh3aW4sIHRleHQ9cHJvbXB0LCBiZz1CT0RZX0NPTE9SLCBmZz1U"
    "RVhUX0NPTE9SLCBmb250PUZPTlRfTk9STUFMLCBhbmNob3I9InciLAogICAgICAgICAgICAganVz"
    "dGlmeT0ibGVmdCIsIHdyYXBsZW5ndGg9d2lkdGggLSAyICogTUFSR0lOKS5wYWNrKGZpbGw9Ingi"
    "LCBwYWR4PU1BUkdJTiwgcGFkeT0oTUFSR0lOLCA2KSkKCiAgICBlbnRyeSA9IE5vbmUKICAgIHZh"
    "ciA9IE5vbmUKICAgIGlmIG11bHRpbGluZToKICAgICAgICBmcmFtZSA9IHRrLkZyYW1lKHdpbiwg"
    "Ymc9Qk9SREVSX0NPTE9SKQogICAgICAgIGZyYW1lLnBhY2soZmlsbD0iYm90aCIsIGV4cGFuZD1U"
    "cnVlLCBwYWR4PU1BUkdJTiwgcGFkeT0oMCwgNikpCiAgICAgICAgZW50cnkgPSB0ay5UZXh0KGZy"
    "YW1lLCBoZWlnaHQ9OCwgYmc9RURJVF9CR19DT0xPUiwgZmc9VEVYVF9DT0xPUiwgaW5zZXJ0YmFj"
    "a2dyb3VuZD1URVhUX0NPTE9SLAogICAgICAgICAgICAgICAgICAgICAgICAgcmVsaWVmPSJmbGF0"
    "Iiwgd3JhcD0id29yZCIsIGZvbnQ9Rk9OVF9OT1JNQUwpCiAgICAgICAgZW50cnkucGFjayhmaWxs"
    "PSJib3RoIiwgZXhwYW5kPVRydWUsIHBhZHg9MSwgcGFkeT0xKQogICAgICAgIGlmIGRlZmF1bHQ6"
    "CiAgICAgICAgICAgIGVudHJ5Lmluc2VydCgiMS4wIiwgZGVmYXVsdCkKICAgICAgICBpZiByZWFk"
    "X29ubHk6CiAgICAgICAgICAgIGVudHJ5LmNvbmZpZ3VyZShzdGF0ZT0iZGlzYWJsZWQiKQogICAg"
    "ZWxzZToKICAgICAgICB2YXIgPSB0ay5TdHJpbmdWYXIodmFsdWU9ZGVmYXVsdCkKICAgICAgICBl"
    "bnRyeSA9IHRrLkVudHJ5KHdpbiwgdGV4dHZhcmlhYmxlPXZhciwgc2hvdz0iKiIgaWYgbWFza2Vk"
    "IGVsc2UgIiIsIGJnPUVESVRfQkdfQ09MT1IsIGZnPVRFWFRfQ09MT1IsCiAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgaW5zZXJ0YmFja2dyb3VuZD1URVhUX0NPTE9SLCByZWxpZWY9ImZsYXQiLCBm"
    "b250PUZPTlRfTk9STUFMLCBoaWdobGlnaHR0aGlja25lc3M9MSwKICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICBoaWdobGlnaHRiYWNrZ3JvdW5kPUJPUkRFUl9DT0xPUiwgaGlnaGxpZ2h0Y29sb3I9"
    "QlROX1BSSU1BUllfQkcpCiAgICAgICAgZW50cnkucGFjayhmaWxsPSJ4IiwgcGFkeD1NQVJHSU4s"
    "IHBhZHk9KDAsIDYpLCBpcGFkeT00KQogICAgICAgIGlmIHJlYWRfb25seToKICAgICAgICAgICAg"
    "ZW50cnkuY29uZmlndXJlKHN0YXRlPSJyZWFkb25seSIsIHJlYWRvbmx5YmFja2dyb3VuZD1FRElU"
    "X0JHX0NPTE9SKQoKICAgIGRlZiBnZXRfdmFsdWUoKToKICAgICAgICBpZiBtdWx0aWxpbmU6CiAg"
    "ICAgICAgICAgIHByZXZfc3RhdGUgPSBzdHIoZW50cnkuY2dldCgic3RhdGUiKSkKICAgICAgICAg"
    "ICAgaWYgcHJldl9zdGF0ZSA9PSAiZGlzYWJsZWQiOgogICAgICAgICAgICAgICAgZW50cnkuY29u"
    "ZmlndXJlKHN0YXRlPSJub3JtYWwiKQogICAgICAgICAgICAgICAgdmFsID0gZW50cnkuZ2V0KCIx"
    "LjAiLCAiZW5kLTFjIikKICAgICAgICAgICAgICAgIGVudHJ5LmNvbmZpZ3VyZShzdGF0ZT0iZGlz"
    "YWJsZWQiKQogICAgICAgICAgICAgICAgcmV0dXJuIHZhbAogICAgICAgICAgICByZXR1cm4gZW50"
    "cnkuZ2V0KCIxLjAiLCAiZW5kLTFjIikKICAgICAgICByZXR1cm4gdmFyLmdldCgpCgogICAgZGVm"
    "IG9uX29rKCk6CiAgICAgICAgcmVzdWx0WyJ2YWx1ZSJdID0gZ2V0X3ZhbHVlKCkKICAgICAgICBy"
    "ZXN1bHRbIm9rIl0gPSBUcnVlCiAgICAgICAgd2luLmRlc3Ryb3koKQoKICAgIGRlZiBvbl9jYW5j"
    "ZWwoKToKICAgICAgICByZXN1bHRbIm9rIl0gPSBGYWxzZQogICAgICAgIHdpbi5kZXN0cm95KCkK"
    "CiAgICBkZWYgb25fY29weSgpOgogICAgICAgIHdpbi5jbGlwYm9hcmRfY2xlYXIoKQogICAgICAg"
    "IHdpbi5jbGlwYm9hcmRfYXBwZW5kKGdldF92YWx1ZSgpKQoKICAgIGJ0bl9mcmFtZSA9IHRrLkZy"
    "YW1lKHdpbiwgYmc9Qk9EWV9DT0xPUikKICAgIGJ0bl9mcmFtZS5wYWNrKGZpbGw9IngiLCBwYWR4"
    "PU1BUkdJTiwgcGFkeT0oNiwgTUFSR0lOKSkKCiAgICBpZiByZWFkX29ubHk6CiAgICAgICAgUm91"
    "bmRlZEJ1dHRvbihidG5fZnJhbWUsICJDb3B5IHRvIENsaXBib2FyZCIsIGNvbW1hbmQ9b25fY29w"
    "eSwgd2lkdGg9MTcwLCBoZWlnaHQ9MzApLnBhY2soc2lkZT0ibGVmdCIpCiAgICAgICAgUm91bmRl"
    "ZEJ1dHRvbihidG5fZnJhbWUsICJDbG9zZSIsIGNvbW1hbmQ9b25fY2FuY2VsLCB3aWR0aD05MCwg"
    "aGVpZ2h0PTMwLCBwcmltYXJ5PVRydWUpLnBhY2soc2lkZT0icmlnaHQiKQogICAgZWxzZToKICAg"
    "ICAgICBSb3VuZGVkQnV0dG9uKGJ0bl9mcmFtZSwgIkNhbmNlbCIsIGNvbW1hbmQ9b25fY2FuY2Vs"
    "LCB3aWR0aD05MCwgaGVpZ2h0PTMwKS5wYWNrKHNpZGU9InJpZ2h0IikKICAgICAgICBSb3VuZGVk"
    "QnV0dG9uKGJ0bl9mcmFtZSwgIk9LIiwgY29tbWFuZD1vbl9vaywgd2lkdGg9OTAsIGhlaWdodD0z"
    "MCwgcHJpbWFyeT1UcnVlKS5wYWNrKHNpZGU9InJpZ2h0IiwgcGFkeD0oMCwgOCkpCgogICAgZGVm"
    "IG9uX3JldHVybihfZSk6CiAgICAgICAgaWYgcmVhZF9vbmx5OgogICAgICAgICAgICBvbl9jYW5j"
    "ZWwoKQogICAgICAgIGVsaWYgbXVsdGlsaW5lIGFuZCB3aW4uZm9jdXNfZ2V0KCkgaXMgZW50cnk6"
    "CiAgICAgICAgICAgIHJldHVybgogICAgICAgIGVsc2U6CiAgICAgICAgICAgIG9uX29rKCkKCiAg"
    "ICB3aW4uYmluZCgiPFJldHVybj4iLCBvbl9yZXR1cm4pCiAgICB3aW4uYmluZCgiPEVzY2FwZT4i"
    "LCBsYW1iZGEgZTogb25fY2FuY2VsKCkpCiAgICB3aW4ucHJvdG9jb2woIldNX0RFTEVURV9XSU5E"
    "T1ciLCBvbl9jYW5jZWwpCgogICAgZW50cnkuZm9jdXNfc2V0KCkKICAgIGNlbnRlcl93aW5kb3co"
    "d2luLCBwYXJlbnQsIHdpZHRoLCBoZWlnaHQpCiAgICB3aW4uZ3JhYl9zZXQoKQogICAgd2luLndh"
    "aXRfd2luZG93KCkKICAgIHJldHVybiByZXN1bHRbInZhbHVlIl0sIHJlc3VsdFsib2siXQoKCmRl"
    "ZiBzaG93X2NvcHlhYmxlX2RpYWxvZyhwYXJlbnQsIHRpdGxlLCBwcm9tcHQsIHRleHQsIG11bHRp"
    "bGluZSk6CiAgICBzaG93X2lucHV0X2RpYWxvZyhwYXJlbnQsIHRpdGxlLCBwcm9tcHQsIG1hc2tl"
    "ZD1GYWxzZSwgbXVsdGlsaW5lPW11bHRpbGluZSwgZGVmYXVsdD10ZXh0LCByZWFkX29ubHk9VHJ1"
    "ZSkKCgpkZWYgc2hvd19jaG9pY2VfZGlhbG9nKHBhcmVudCwgdGl0bGUsIG1lc3NhZ2UsIG9wdGlv"
    "bjEsIG9wdGlvbjIpOgogICAgcmVzdWx0ID0geyJjaG9pY2UiOiAwfQogICAgd2luID0gdGsuVG9w"
    "bGV2ZWwocGFyZW50KQogICAgd2luLnRpdGxlKHRpdGxlKQogICAgd2luLmNvbmZpZ3VyZShiZz1C"
    "T0RZX0NPTE9SKQogICAgd2luLnJlc2l6YWJsZShGYWxzZSwgRmFsc2UpCiAgICB3aW4udHJhbnNp"
    "ZW50KHBhcmVudCkKICAgIHdpZHRoLCBoZWlnaHQgPSA0NDAsIDE3MAogICAgYXBwbHlfZGFya190"
    "aXRsZWJhcih3aW4pCgogICAgdGsuTGFiZWwod2luLCB0ZXh0PW1lc3NhZ2UsIGJnPUJPRFlfQ09M"
    "T1IsIGZnPVRFWFRfQ09MT1IsIGZvbnQ9Rk9OVF9OT1JNQUwsIGp1c3RpZnk9ImxlZnQiLAogICAg"
    "ICAgICAgICAgd3JhcGxlbmd0aD13aWR0aCAtIDIgKiBNQVJHSU4sIGFuY2hvcj0idyIpLnBhY2so"
    "cGFkeD1NQVJHSU4sIHBhZHk9KE1BUkdJTiwgMTQpLCBmaWxsPSJ4IikKCiAgICBidG5fZnJhbWUg"
    "PSB0ay5GcmFtZSh3aW4sIGJnPUJPRFlfQ09MT1IpCiAgICBidG5fZnJhbWUucGFjaygpCgogICAg"
    "ZGVmIHBpY2sobik6CiAgICAgICAgcmVzdWx0WyJjaG9pY2UiXSA9IG4KICAgICAgICB3aW4uZGVz"
    "dHJveSgpCgogICAgUm91bmRlZEJ1dHRvbihidG5fZnJhbWUsIG9wdGlvbjEsIGNvbW1hbmQ9bGFt"
    "YmRhOiBwaWNrKDEpLCB3aWR0aD0xNzAsIGhlaWdodD0zNCwgcHJpbWFyeT1UcnVlKS5wYWNrKHNp"
    "ZGU9ImxlZnQiLCBwYWR4PTgpCiAgICBSb3VuZGVkQnV0dG9uKGJ0bl9mcmFtZSwgb3B0aW9uMiwg"
    "Y29tbWFuZD1sYW1iZGE6IHBpY2soMiksIHdpZHRoPTE3MCwgaGVpZ2h0PTM0KS5wYWNrKHNpZGU9"
    "ImxlZnQiLCBwYWR4PTgpCgogICAgd2luLnByb3RvY29sKCJXTV9ERUxFVEVfV0lORE9XIiwgbGFt"
    "YmRhOiBwaWNrKDApKQogICAgd2luLmJpbmQoIjxSZXR1cm4+IiwgbGFtYmRhIGU6IHBpY2soMSkp"
    "CiAgICB3aW4uYmluZCgiPEVzY2FwZT4iLCBsYW1iZGEgZTogcGljaygwKSkKCiAgICBjZW50ZXJf"
    "d2luZG93KHdpbiwgcGFyZW50LCB3aWR0aCwgaGVpZ2h0KQogICAgd2luLmdyYWJfc2V0KCkKICAg"
    "IHdpbi53YWl0X3dpbmRvdygpCiAgICByZXR1cm4gcmVzdWx0WyJjaG9pY2UiXQoKCmRlZiBvYnRh"
    "aW5fcGFzc3BocmFzZV9ndWkocGFyZW50LCBsYWJlbCk6CiAgICBjaG9pY2UgPSBzaG93X2Nob2lj"
    "ZV9kaWFsb2cocGFyZW50LCBmIntsYWJlbC5jYXBpdGFsaXplKCl9IHBhc3NwaHJhc2UiLAogICAg"
    "ICAgIGYiR2VuZXJhdGUgYSBzdHJvbmcgcmFuZG9tIHtsYWJlbH0gcGFzc3BocmFzZSxcbm9yIGVu"
    "dGVyIHlvdXIgb3duPyIsICJHZW5lcmF0ZSBmb3IgbWUiLCAiSSdsbCBlbnRlciBteSBvd24iKQog"
    "ICAgaWYgY2hvaWNlID09IDA6CiAgICAgICAgcmV0dXJuICIiCiAgICBpZiBjaG9pY2UgPT0gMToK"
    "ICAgICAgICBnZW5lcmF0ZWQgPSBnZW5lcmF0ZV9wYXNzcGhyYXNlKCkKICAgICAgICBzaG93X21l"
    "c3NhZ2UocGFyZW50LCBmIkdlbmVyYXRlZCB7bGFiZWx9IHBhc3NwaHJhc2UiLAogICAgICAgICAg"
    "ICAiQSByYW5kb20gcGFzc3BocmFzZSBoYXMgYmVlbiBnZW5lcmF0ZWQgZm9yIHlvdS5cblxuIgog"
    "ICAgICAgICAgICAiSXQgaXMgc2hvd24gT05MWSBPTkNFIGFuZCBpcyBuZXZlciBzYXZlZCBieSB0"
    "aGlzIHByb2dyYW0uXG4iCiAgICAgICAgICAgICJXcml0ZSBpdCBkb3duIG5vdyAocGFzc3dvcmQg"
    "bWFuYWdlciwgcGFwZXIsIGV0Yy4pIC0tIHdpdGhvdXQgaXQsXG4iCiAgICAgICAgICAgICJ0aGlz"
    "IGNhbiBORVZFUiBiZSBkZWNyeXB0ZWQgYWdhaW4sIGJ5IHRoaXMgcHJvZ3JhbSBvciBhbnlvbmUg"
    "ZWxzZS4iKQogICAgICAgIHNob3dfY29weWFibGVfZGlhbG9nKHBhcmVudCwgZiJZb3VyIGdlbmVy"
    "YXRlZCB7bGFiZWx9IHBhc3NwaHJhc2UiLCAiQ29weSB0aGlzIG5vdyAtLSBpdCB3aWxsIG5vdCBi"
    "ZSBzaG93biBhZ2FpbjoiLCBnZW5lcmF0ZWQsIEZhbHNlKQogICAgICAgIHJldHVybiBnZW5lcmF0"
    "ZWQKICAgIHAxLCBvazEgPSBzaG93X2lucHV0X2RpYWxvZyhwYXJlbnQsIGYiRW50ZXIge2xhYmVs"
    "fSBwYXNzcGhyYXNlIiwgZiJFbnRlciB5b3VyIHtsYWJlbH0gcGFzc3BocmFzZToiLCBtYXNrZWQ9"
    "VHJ1ZSkKICAgIGlmIG5vdCBvazE6CiAgICAgICAgcmV0dXJuICIiCiAgICBwMiwgb2syID0gc2hv"
    "d19pbnB1dF9kaWFsb2cocGFyZW50LCBmIkNvbmZpcm0ge2xhYmVsfSBwYXNzcGhyYXNlIiwgZiJD"
    "b25maXJtIHlvdXIge2xhYmVsfSBwYXNzcGhyYXNlOiIsIG1hc2tlZD1UcnVlKQogICAgaWYgbm90"
    "IG9rMjoKICAgICAgICByZXR1cm4gIiIKICAgIGlmIHAxICE9IHAyOgogICAgICAgIHNob3dfbWVz"
    "c2FnZShwYXJlbnQsICJNaXNtYXRjaCIsICJQYXNzcGhyYXNlcyBkaWQgbm90IG1hdGNoLiIsIGlz"
    "X2Vycm9yPVRydWUpCiAgICAgICAgcmV0dXJuICIiCiAgICByZXR1cm4gcDEKCgojID09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PQojICBUZXh0IC8gZmlsZSBhY3Rpb25zCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpkZWYgZG9fZW5jcnlw"
    "dF90ZXh0KHBhcmVudCk6CiAgICBwbGFpbnRleHQsIG9rID0gc2hvd19pbnB1dF9kaWFsb2cocGFy"
    "ZW50LCAiRW5jcnlwdCBUZXh0IiwgIkVudGVyIHRleHQgdG8gZW5jcnlwdDoiLCBtdWx0aWxpbmU9"
    "VHJ1ZSkKICAgIGlmIG5vdCBvayBvciBub3QgcGxhaW50ZXh0OgogICAgICAgIHJldHVybgogICAg"
    "cHJpbWFyeV9wYXNzID0gb2J0YWluX3Bhc3NwaHJhc2VfZ3VpKHBhcmVudCwgInByaW1hcnkiKQog"
    "ICAgaWYgbm90IHByaW1hcnlfcGFzczoKICAgICAgICByZXR1cm4KICAgIHJlY292ZXJ5X3Bhc3Mg"
    "PSBvYnRhaW5fcGFzc3BocmFzZV9ndWkocGFyZW50LCAicmVjb3ZlcnkiKQogICAgaWYgbm90IHJl"
    "Y292ZXJ5X3Bhc3M6CiAgICAgICAgcmV0dXJuCgogICAgZGVrID0gYnl0ZWFycmF5KHNlY3JldHMu"
    "dG9rZW5fYnl0ZXMoS0VZX0xFTikpCiAgICBfbG9jayhkZWspCiAgICB0cnk6CiAgICAgICAgcHJp"
    "bWFyeV93cmFwID0gd3JhcF9rZXkocHJpbWFyeV9wYXNzLCBkZWssIEFBRF9ST0xFX1BSSU1BUlkp"
    "CiAgICAgICAgcmVjb3Zlcnlfd3JhcCA9IHdyYXBfa2V5KHJlY292ZXJ5X3Bhc3MsIGRlaywgQUFE"
    "X1JPTEVfUkVDT1ZFUlkpCiAgICAgICAgZGF0YV9ub25jZSA9IHNlY3JldHMudG9rZW5fYnl0ZXMo"
    "SVZfTEVOKQogICAgICAgIGNpcGhlcnRleHQsIGRhdGFfdGFnID0gYWVzX2djbV9lbmNyeXB0KGRl"
    "aywgZGF0YV9ub25jZSwgcGxhaW50ZXh0LmVuY29kZSgidXRmLTgiKSwgQUFEX1RFWFRfQ1RYKQog"
    "ICAgZXhjZXB0IEJDcnlwdEVycm9yIGFzIGU6CiAgICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwg"
    "IkVycm9yIiwgZiJFbmNyeXB0aW9uIGZhaWxlZC5cbntlfSIsIGlzX2Vycm9yPVRydWUpCiAgICAg"
    "ICAgcmV0dXJuCiAgICBmaW5hbGx5OgogICAgICAgIF96ZXJvKGRlaykKICAgICAgICBfdW5sb2Nr"
    "KGRlaykKCiAgICBwYWNrZWQgPSB3cmFwX3RvX2J5dGVzKHByaW1hcnlfd3JhcCkgKyB3cmFwX3Rv"
    "X2J5dGVzKHJlY292ZXJ5X3dyYXApICsgZGF0YV9ub25jZSArIGRhdGFfdGFnICsgY2lwaGVydGV4"
    "dAogICAgc2hvd19jb3B5YWJsZV9kaWFsb2cocGFyZW50LCAiRW5jcnlwdGVkIHRleHQiLCAiWW91"
    "ciBlbmNyeXB0ZWQgdGV4dCAoY29weSBhbmQgc3RvcmUgaXQpOiIsIHRvX2hleChwYWNrZWQpLCBU"
    "cnVlKQoKCmRlZiBkb19kZWNyeXB0X3RleHQocGFyZW50KToKICAgIHBhY2tlZF9oZXgsIG9rID0g"
    "c2hvd19pbnB1dF9kaWFsb2cocGFyZW50LCAiRGVjcnlwdCBUZXh0IiwgIlBhc3RlIGVuY3J5cHRl"
    "ZCB0ZXh0OiIsIG11bHRpbGluZT1UcnVlKQogICAgaWYgbm90IG9rIG9yIG5vdCBwYWNrZWRfaGV4"
    "OgogICAgICAgIHJldHVybgogICAgdHJ5OgogICAgICAgIHJhdyA9IGZyb21faGV4KHBhY2tlZF9o"
    "ZXgpCiAgICBleGNlcHQgVmFsdWVFcnJvcjoKICAgICAgICBzaG93X21lc3NhZ2UocGFyZW50LCAi"
    "RXJyb3IiLCAiVGhhdCBkb2Vzbid0IGxvb2sgbGlrZSB2YWxpZCBlbmNyeXB0ZWQgdGV4dCAoaW52"
    "YWxpZCBoZXggZGF0YSkuIiwgaXNfZXJyb3I9VHJ1ZSkKICAgICAgICByZXR1cm4KCiAgICBoZWFk"
    "ZXJfbGVuID0gV1JBUF9MRU4gKiAyICsgSVZfTEVOICsgVEFHX0xFTgogICAgaWYgbGVuKHJhdykg"
    "PCBoZWFkZXJfbGVuOgogICAgICAgIHNob3dfbWVzc2FnZShwYXJlbnQsICJFcnJvciIsICJUaGF0"
    "IGRvZXNuJ3QgbG9vayBsaWtlIHZhbGlkIGVuY3J5cHRlZCBkYXRhLiIsIGlzX2Vycm9yPVRydWUp"
    "CiAgICAgICAgcmV0dXJuCgogICAgcHJpbWFyeV93cmFwID0gd3JhcF9mcm9tX2J5dGVzKHJhd1sw"
    "OldSQVBfTEVOXSkKICAgIHJlY292ZXJ5X3dyYXAgPSB3cmFwX2Zyb21fYnl0ZXMocmF3W1dSQVBf"
    "TEVOOldSQVBfTEVOICogMl0pCiAgICBwb3MgPSBXUkFQX0xFTiAqIDIKICAgIGRhdGFfbm9uY2Ug"
    "PSByYXdbcG9zOnBvcyArIElWX0xFTl07IHBvcyArPSBJVl9MRU4KICAgIGRhdGFfdGFnID0gcmF3"
    "W3Bvczpwb3MgKyBUQUdfTEVOXTsgcG9zICs9IFRBR19MRU4KICAgIGNpcGhlcnRleHQgPSByYXdb"
    "cG9zOl0KCiAgICB3aGljaCA9IHNob3dfY2hvaWNlX2RpYWxvZyhwYXJlbnQsICJVbmxvY2siLCAi"
    "VW5sb2NrIHdpdGggd2hpY2ggcGFzc3BocmFzZT8iLCAiUHJpbWFyeSIsICJSZWNvdmVyeSIpCiAg"
    "ICBpZiB3aGljaCA9PSAwOgogICAgICAgIHJldHVybgogICAgcGFzc3BocmFzZSwgb2sgPSBzaG93"
    "X2lucHV0X2RpYWxvZyhwYXJlbnQsICJQYXNzcGhyYXNlIiwgIkVudGVyIHBhc3NwaHJhc2U6Iiwg"
    "bWFza2VkPVRydWUpCiAgICBpZiBub3Qgb2s6CiAgICAgICAgcmV0dXJuCgogICAgcm9sZV9hYWQg"
    "PSBBQURfUk9MRV9SRUNPVkVSWSBpZiB3aGljaCA9PSAyIGVsc2UgQUFEX1JPTEVfUFJJTUFSWQog"
    "ICAgd3JhcCA9IHJlY292ZXJ5X3dyYXAgaWYgd2hpY2ggPT0gMiBlbHNlIHByaW1hcnlfd3JhcAog"
    "ICAgdHJ5OgogICAgICAgIGRlayA9IHVud3JhcF9rZXkocGFzc3BocmFzZSwgd3JhcCwgcm9sZV9h"
    "YWQpCiAgICBleGNlcHQgQkNyeXB0RXJyb3I6CiAgICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwg"
    "IkZhaWxlZCIsICJXcm9uZyBwYXNzcGhyYXNlIGZvciB0aGF0IG9wdGlvbiAob3IgdGhlIGRhdGEg"
    "aXMgY29ycnVwdGVkKS4iLCBpc19lcnJvcj1UcnVlKQogICAgICAgIHJldHVybgogICAgdHJ5Ogog"
    "ICAgICAgIHBsYWludGV4dCA9IGFlc19nY21fZGVjcnlwdChkZWssIGRhdGFfbm9uY2UsIGNpcGhl"
    "cnRleHQsIGRhdGFfdGFnLCBBQURfVEVYVF9DVFgpCiAgICBleGNlcHQgQkNyeXB0RXJyb3I6CiAg"
    "ICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwgIkZhaWxlZCIsICJUaGUgZGF0YSBhcHBlYXJzIHRv"
    "IGJlIGNvcnJ1cHRlZCBvciB0YW1wZXJlZCB3aXRoLiIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAg"
    "cmV0dXJuCiAgICBmaW5hbGx5OgogICAgICAgIF96ZXJvKGRlaykKICAgICAgICBfdW5sb2NrKGRl"
    "aykKCiAgICBzaG93X2NvcHlhYmxlX2RpYWxvZyhwYXJlbnQsICJEZWNyeXB0ZWQgdGV4dCIsICJE"
    "ZWNyeXB0ZWQgcmVzdWx0OiIsIHBsYWludGV4dC5kZWNvZGUoInV0Zi04IiwgZXJyb3JzPSJyZXBs"
    "YWNlIiksIFRydWUpCgoKZGVmIGRvX2VuY3J5cHRfZmlsZShwYXJlbnQpOgogICAgaW5fcGF0aCA9"
    "IGZpbGVkaWFsb2cuYXNrb3BlbmZpbGVuYW1lKHBhcmVudD1wYXJlbnQsIHRpdGxlPSJDaG9vc2Ug"
    "YSBmaWxlIHRvIGVuY3J5cHQiKQogICAgaWYgbm90IGluX3BhdGg6CiAgICAgICAgcmV0dXJuCiAg"
    "ICB0cnk6CiAgICAgICAgd2l0aCBvcGVuKGluX3BhdGgsICJyYiIpIGFzIGY6CiAgICAgICAgICAg"
    "IGZpbGVfYnl0ZXMgPSBmLnJlYWQoKQogICAgZXhjZXB0IE9TRXJyb3IgYXMgZToKICAgICAgICBz"
    "aG93X21lc3NhZ2UocGFyZW50LCAiRXJyb3IiLCBmIkNvdWxkIG5vdCBvcGVuIHRoYXQgZmlsZS5c"
    "bntlfSIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAgcmV0dXJuCgogICAgZXh0X2J5dGVzID0gb3Mu"
    "cGF0aC5zcGxpdGV4dChpbl9wYXRoKVsxXS5lbmNvZGUoInV0Zi04IikKICAgIGNvbWJpbmVkID0g"
    "Ynl0ZWFycmF5KHN0cnVjdC5wYWNrKCI8SSIsIGxlbihleHRfYnl0ZXMpKSArIGV4dF9ieXRlcyAr"
    "IGZpbGVfYnl0ZXMpCgogICAgZGVmYXVsdF9uYW1lID0gb3MucGF0aC5iYXNlbmFtZShpbl9wYXRo"
    "KSArICIuZW5jIgogICAgb3V0X3BhdGggPSBmaWxlZGlhbG9nLmFza3NhdmVhc2ZpbGVuYW1lKHBh"
    "cmVudD1wYXJlbnQsIHRpdGxlPSJTYXZlIGVuY3J5cHRlZCBmaWxlIGFzIiwgaW5pdGlhbGZpbGU9"
    "ZGVmYXVsdF9uYW1lKQogICAgaWYgbm90IG91dF9wYXRoOgogICAgICAgIHJldHVybgoKICAgIHBy"
    "aW1hcnlfcGFzcyA9IG9idGFpbl9wYXNzcGhyYXNlX2d1aShwYXJlbnQsICJwcmltYXJ5IikKICAg"
    "IGlmIG5vdCBwcmltYXJ5X3Bhc3M6CiAgICAgICAgcmV0dXJuCiAgICByZWNvdmVyeV9wYXNzID0g"
    "b2J0YWluX3Bhc3NwaHJhc2VfZ3VpKHBhcmVudCwgInJlY292ZXJ5IikKICAgIGlmIG5vdCByZWNv"
    "dmVyeV9wYXNzOgogICAgICAgIHJldHVybgoKICAgIGRlayA9IGJ5dGVhcnJheShzZWNyZXRzLnRv"
    "a2VuX2J5dGVzKEtFWV9MRU4pKQogICAgX2xvY2soZGVrKQogICAgdHJ5OgogICAgICAgIHByaW1h"
    "cnlfd3JhcCA9IHdyYXBfa2V5KHByaW1hcnlfcGFzcywgZGVrLCBBQURfUk9MRV9QUklNQVJZKQog"
    "ICAgICAgIHJlY292ZXJ5X3dyYXAgPSB3cmFwX2tleShyZWNvdmVyeV9wYXNzLCBkZWssIEFBRF9S"
    "T0xFX1JFQ09WRVJZKQogICAgICAgIGRhdGFfbm9uY2UgPSBzZWNyZXRzLnRva2VuX2J5dGVzKElW"
    "X0xFTikKICAgICAgICBjaXBoZXJ0ZXh0LCBkYXRhX3RhZyA9IGFlc19nY21fZW5jcnlwdChkZWss"
    "IGRhdGFfbm9uY2UsIGJ5dGVzKGNvbWJpbmVkKSwgQUFEX0ZJTEVfQ1RYKQogICAgZXhjZXB0IEJD"
    "cnlwdEVycm9yIGFzIGU6CiAgICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwgIkVycm9yIiwgZiJF"
    "bmNyeXB0aW9uIGZhaWxlZC5cbntlfSIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAgcmV0dXJuCiAg"
    "ICBmaW5hbGx5OgogICAgICAgIF96ZXJvKGRlaykKICAgICAgICBfdW5sb2NrKGRlaykKICAgICAg"
    "ICBfemVybyhjb21iaW5lZCkKCiAgICB0cnk6CiAgICAgICAgd2l0aCBvcGVuKG91dF9wYXRoLCAi"
    "d2IiKSBhcyBmOgogICAgICAgICAgICBmLndyaXRlKE1BR0lDKQogICAgICAgICAgICBmLndyaXRl"
    "KHdyYXBfdG9fYnl0ZXMocHJpbWFyeV93cmFwKSkKICAgICAgICAgICAgZi53cml0ZSh3cmFwX3Rv"
    "X2J5dGVzKHJlY292ZXJ5X3dyYXApKQogICAgICAgICAgICBmLndyaXRlKGRhdGFfbm9uY2UpCiAg"
    "ICAgICAgICAgIGYud3JpdGUoZGF0YV90YWcpCiAgICAgICAgICAgIGYud3JpdGUoY2lwaGVydGV4"
    "dCkKICAgIGV4Y2VwdCBPU0Vycm9yIGFzIGU6CiAgICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwg"
    "IkVycm9yIiwgZiJDb3VsZCBub3Qgd3JpdGUgb3V0cHV0IGZpbGUuXG57ZX0iLCBpc19lcnJvcj1U"
    "cnVlKQogICAgICAgIHJldHVybgoKICAgIHNob3dfbWVzc2FnZShwYXJlbnQsICJEb25lIiwgZiJF"
    "bmNyeXB0ZWQgZmlsZSB3cml0dGVuIHRvOlxue291dF9wYXRofSIpCgoKZGVmIGRvX2RlY3J5cHRf"
    "ZmlsZShwYXJlbnQpOgogICAgaW5fcGF0aCA9IGZpbGVkaWFsb2cuYXNrb3BlbmZpbGVuYW1lKHBh"
    "cmVudD1wYXJlbnQsIHRpdGxlPSJDaG9vc2UgYSBmaWxlIHRvIGRlY3J5cHQiKQogICAgaWYgbm90"
    "IGluX3BhdGg6CiAgICAgICAgcmV0dXJuCiAgICB0cnk6CiAgICAgICAgd2l0aCBvcGVuKGluX3Bh"
    "dGgsICJyYiIpIGFzIGY6CiAgICAgICAgICAgIHJhdyA9IGYucmVhZCgpCiAgICBleGNlcHQgT1NF"
    "cnJvciBhcyBlOgogICAgICAgIHNob3dfbWVzc2FnZShwYXJlbnQsICJFcnJvciIsIGYiQ291bGQg"
    "bm90IG9wZW4gdGhhdCBmaWxlLlxue2V9IiwgaXNfZXJyb3I9VHJ1ZSkKICAgICAgICByZXR1cm4K"
    "CiAgICBoZWFkZXJfbGVuID0gNCArIFdSQVBfTEVOICogMiArIElWX0xFTiArIFRBR19MRU4KICAg"
    "IGlmIGxlbihyYXcpIDwgaGVhZGVyX2xlbiBvciByYXdbOjRdICE9IE1BR0lDOgogICAgICAgIHNo"
    "b3dfbWVzc2FnZShwYXJlbnQsICJFcnJvciIsICJUaGlzIGRvZXMgbm90IGxvb2sgbGlrZSBhIGZp"
    "bGUgY3JlYXRlZCBieSB0aGlzIHByb2dyYW0uIiwgaXNfZXJyb3I9VHJ1ZSkKICAgICAgICByZXR1"
    "cm4KCiAgICBwb3MgPSA0CiAgICBwcmltYXJ5X3dyYXAgPSB3cmFwX2Zyb21fYnl0ZXMocmF3W3Bv"
    "czpwb3MgKyBXUkFQX0xFTl0pOyBwb3MgKz0gV1JBUF9MRU4KICAgIHJlY292ZXJ5X3dyYXAgPSB3"
    "cmFwX2Zyb21fYnl0ZXMocmF3W3Bvczpwb3MgKyBXUkFQX0xFTl0pOyBwb3MgKz0gV1JBUF9MRU4K"
    "ICAgIGRhdGFfbm9uY2UgPSByYXdbcG9zOnBvcyArIElWX0xFTl07IHBvcyArPSBJVl9MRU4KICAg"
    "IGRhdGFfdGFnID0gcmF3W3Bvczpwb3MgKyBUQUdfTEVOXTsgcG9zICs9IFRBR19MRU4KICAgIGNp"
    "cGhlcnRleHQgPSByYXdbcG9zOl0KCiAgICB3aGljaCA9IHNob3dfY2hvaWNlX2RpYWxvZyhwYXJl"
    "bnQsICJVbmxvY2siLCAiVW5sb2NrIHdpdGggd2hpY2ggcGFzc3BocmFzZT8iLCAiUHJpbWFyeSIs"
    "ICJSZWNvdmVyeSIpCiAgICBpZiB3aGljaCA9PSAwOgogICAgICAgIHJldHVybgogICAgcGFzc3Bo"
    "cmFzZSwgb2sgPSBzaG93X2lucHV0X2RpYWxvZyhwYXJlbnQsICJQYXNzcGhyYXNlIiwgIkVudGVy"
    "IHBhc3NwaHJhc2U6IiwgbWFza2VkPVRydWUpCiAgICBpZiBub3Qgb2s6CiAgICAgICAgcmV0dXJu"
    "CgogICAgcm9sZV9hYWQgPSBBQURfUk9MRV9SRUNPVkVSWSBpZiB3aGljaCA9PSAyIGVsc2UgQUFE"
    "X1JPTEVfUFJJTUFSWQogICAgd3JhcCA9IHJlY292ZXJ5X3dyYXAgaWYgd2hpY2ggPT0gMiBlbHNl"
    "IHByaW1hcnlfd3JhcAogICAgdHJ5OgogICAgICAgIGRlayA9IHVud3JhcF9rZXkocGFzc3BocmFz"
    "ZSwgd3JhcCwgcm9sZV9hYWQpCiAgICBleGNlcHQgQkNyeXB0RXJyb3I6CiAgICAgICAgc2hvd19t"
    "ZXNzYWdlKHBhcmVudCwgIkZhaWxlZCIsICJXcm9uZyBwYXNzcGhyYXNlIGZvciB0aGF0IG9wdGlv"
    "biAob3IgdGhlIGZpbGUgaXMgY29ycnVwdGVkKS4iLCBpc19lcnJvcj1UcnVlKQogICAgICAgIHJl"
    "dHVybgogICAgdHJ5OgogICAgICAgIGNvbWJpbmVkID0gYWVzX2djbV9kZWNyeXB0KGRlaywgZGF0"
    "YV9ub25jZSwgY2lwaGVydGV4dCwgZGF0YV90YWcsIEFBRF9GSUxFX0NUWCkKICAgIGV4Y2VwdCBC"
    "Q3J5cHRFcnJvcjoKICAgICAgICBzaG93X21lc3NhZ2UocGFyZW50LCAiRmFpbGVkIiwgIlRoZSBm"
    "aWxlIGFwcGVhcnMgdG8gYmUgY29ycnVwdGVkIG9yIHRhbXBlcmVkIHdpdGguIiwgaXNfZXJyb3I9"
    "VHJ1ZSkKICAgICAgICByZXR1cm4KICAgIGZpbmFsbHk6CiAgICAgICAgX3plcm8oZGVrKQogICAg"
    "ICAgIF91bmxvY2soZGVrKQoKICAgIGV4dF9sZW4gPSBzdHJ1Y3QudW5wYWNrX2Zyb20oIjxJIiwg"
    "Y29tYmluZWQsIDApWzBdCiAgICBleHQgPSBjb21iaW5lZFs0OjQgKyBleHRfbGVuXS5kZWNvZGUo"
    "InV0Zi04IiwgZXJyb3JzPSJyZXBsYWNlIikKICAgIGZpbGVfZGF0YSA9IGNvbWJpbmVkWzQgKyBl"
    "eHRfbGVuOl0KCiAgICBiYXNlID0gaW5fcGF0aFs6LTRdIGlmIGluX3BhdGgubG93ZXIoKS5lbmRz"
    "d2l0aCgiLmVuYyIpIGVsc2UgaW5fcGF0aAogICAgaWYgbm90IG9zLnBhdGguc3BsaXRleHQoYmFz"
    "ZSlbMV0gYW5kIGV4dDoKICAgICAgICBiYXNlICs9IGV4dAogICAgb3V0X3BhdGggPSBmaWxlZGlh"
    "bG9nLmFza3NhdmVhc2ZpbGVuYW1lKHBhcmVudD1wYXJlbnQsIHRpdGxlPSJTYXZlIGRlY3J5cHRl"
    "ZCBmaWxlIGFzIiwgaW5pdGlhbGZpbGU9b3MucGF0aC5iYXNlbmFtZShiYXNlKSkKICAgIGlmIG5v"
    "dCBvdXRfcGF0aDoKICAgICAgICBfemVybyhjb21iaW5lZCkKICAgICAgICByZXR1cm4KICAgIHRy"
    "eToKICAgICAgICB3aXRoIG9wZW4ob3V0X3BhdGgsICJ3YiIpIGFzIGY6CiAgICAgICAgICAgIGYu"
    "d3JpdGUoZmlsZV9kYXRhKQogICAgZXhjZXB0IE9TRXJyb3IgYXMgZToKICAgICAgICBzaG93X21l"
    "c3NhZ2UocGFyZW50LCAiRXJyb3IiLCBmIkNvdWxkIG5vdCB3cml0ZSBvdXRwdXQgZmlsZS5cbntl"
    "fSIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAgX3plcm8oY29tYmluZWQpCiAgICAgICAgcmV0dXJu"
    "CgogICAgX3plcm8oY29tYmluZWQpCiAgICBzaG93X21lc3NhZ2UocGFyZW50LCAiRG9uZSIsIGYi"
    "RGVjcnlwdGVkIGZpbGUgd3JpdHRlbiB0bzpcbntvdXRfcGF0aH0iKQoKCiMgPT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "CiMgIFBhc3N3b3JkIHZhdWx0CiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpjbGFzcyBWYXVsdFNlc3Npb246CiAg"
    "ICBkZWYgX19pbml0X18oc2VsZiwgcGF0aCk6CiAgICAgICAgc2VsZi5wYXRoID0gcGF0aAogICAg"
    "ICAgIHNlbGYuZGVrID0gYnl0ZWFycmF5KCkKICAgICAgICBzZWxmLnByaW1hcnlfd3JhcCA9IE5v"
    "bmUKICAgICAgICBzZWxmLnJlY292ZXJ5X3dyYXAgPSBOb25lCiAgICAgICAgc2VsZi5lbnRyaWVz"
    "ID0gW10KICAgICAgICBzZWxmLm1vZGlmaWVkID0gRmFsc2UKCiAgICBkZWYgd2lwZShzZWxmKToK"
    "ICAgICAgICBfemVybyhzZWxmLmRlaykKICAgICAgICBfdW5sb2NrKHNlbGYuZGVrKQogICAgICAg"
    "IHNlbGYuZGVrID0gYnl0ZWFycmF5KCkKCgpkZWYgZGVmYXVsdF92YXVsdF9wYXRoKCk6CiAgICBi"
    "YXNlX2RpciA9IG9zLnBhdGguZGlybmFtZShvcy5wYXRoLmFic3BhdGgoc3lzLmFyZ3ZbMF0pKQog"
    "ICAgcmV0dXJuIG9zLnBhdGguam9pbihiYXNlX2RpciwgInZhdWx0LnB5ZW5jIikKCgpkZWYgb3Bl"
    "bl9vcl9jcmVhdGVfdmF1bHRfZ3VpKHBhcmVudCk6CiAgICBkZWZhdWx0X3BhdGggPSBkZWZhdWx0"
    "X3ZhdWx0X3BhdGgoKQogICAgcGF0aCwgb2sgPSBzaG93X2lucHV0X2RpYWxvZyhwYXJlbnQsICJW"
    "YXVsdCBMb2NhdGlvbiIsICJWYXVsdCBmaWxlIHBhdGg6IiwgZGVmYXVsdD1kZWZhdWx0X3BhdGgp"
    "CiAgICBpZiBub3Qgb2sgb3Igbm90IHBhdGg6CiAgICAgICAgcmV0dXJuIE5vbmUKCiAgICBzZXNz"
    "aW9uID0gVmF1bHRTZXNzaW9uKHBhdGgpCgogICAgaWYgbm90IG9zLnBhdGguZXhpc3RzKHBhdGgp"
    "OgogICAgICAgIGNvbmZpcm0gPSBzaG93X2Nob2ljZV9kaWFsb2cocGFyZW50LCAiTmV3IFZhdWx0"
    "IiwgIk5vIHZhdWx0IGZvdW5kIGF0IHRoYXQgcGF0aC5cbkNyZWF0ZSBhIG5ldyBvbmU/IiwgIkNy"
    "ZWF0ZSBuZXcgdmF1bHQiLCAiQ2FuY2VsIikKICAgICAgICBpZiBjb25maXJtICE9IDE6CiAgICAg"
    "ICAgICAgIHJldHVybiBOb25lCiAgICAgICAgcHJpbWFyeV9wYXNzID0gb2J0YWluX3Bhc3NwaHJh"
    "c2VfZ3VpKHBhcmVudCwgInByaW1hcnkiKQogICAgICAgIGlmIG5vdCBwcmltYXJ5X3Bhc3M6CiAg"
    "ICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgcmVjb3ZlcnlfcGFzcyA9IG9idGFpbl9wYXNz"
    "cGhyYXNlX2d1aShwYXJlbnQsICJyZWNvdmVyeSIpCiAgICAgICAgaWYgbm90IHJlY292ZXJ5X3Bh"
    "c3M6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgc2Vzc2lvbi5kZWsgPSBieXRlYXJy"
    "YXkoc2VjcmV0cy50b2tlbl9ieXRlcyhLRVlfTEVOKSkKICAgICAgICBfbG9jayhzZXNzaW9uLmRl"
    "aykKICAgICAgICB0cnk6CiAgICAgICAgICAgIHNlc3Npb24ucHJpbWFyeV93cmFwID0gd3JhcF9r"
    "ZXkocHJpbWFyeV9wYXNzLCBzZXNzaW9uLmRlaywgQUFEX1JPTEVfUFJJTUFSWSkKICAgICAgICAg"
    "ICAgc2Vzc2lvbi5yZWNvdmVyeV93cmFwID0gd3JhcF9rZXkocmVjb3ZlcnlfcGFzcywgc2Vzc2lv"
    "bi5kZWssIEFBRF9ST0xFX1JFQ09WRVJZKQogICAgICAgIGV4Y2VwdCBCQ3J5cHRFcnJvciBhcyBl"
    "OgogICAgICAgICAgICBzaG93X21lc3NhZ2UocGFyZW50LCAiRXJyb3IiLCBmIktleSBzZXR1cCBm"
    "YWlsZWQuXG57ZX0iLCBpc19lcnJvcj1UcnVlKQogICAgICAgICAgICByZXR1cm4gTm9uZQogICAg"
    "ICAgIHNlc3Npb24uZW50cmllcyA9IFtdCiAgICAgICAgc2Vzc2lvbi5tb2RpZmllZCA9IFRydWUK"
    "ICAgICAgICByZXR1cm4gc2Vzc2lvbgoKICAgIHRyeToKICAgICAgICB3aXRoIG9wZW4ocGF0aCwg"
    "InJiIikgYXMgZjoKICAgICAgICAgICAgcmF3ID0gZi5yZWFkKCkKICAgIGV4Y2VwdCBPU0Vycm9y"
    "IGFzIGU6CiAgICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwgIkVycm9yIiwgZiJDb3VsZCBub3Qg"
    "b3BlbiB2YXVsdCBmaWxlLlxue2V9IiwgaXNfZXJyb3I9VHJ1ZSkKICAgICAgICByZXR1cm4gTm9u"
    "ZQoKICAgIGhlYWRlcl9sZW4gPSA0ICsgV1JBUF9MRU4gKiAyICsgSVZfTEVOICsgVEFHX0xFTgog"
    "ICAgaWYgbGVuKHJhdykgPCBoZWFkZXJfbGVuIG9yIHJhd1s6NF0gIT0gVkFVTFRfTUFHSUM6CiAg"
    "ICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwgIkVycm9yIiwgIlRoYXQgZmlsZSBkb2Vzbid0IGxv"
    "b2sgbGlrZSBhIHZhdWx0IGNyZWF0ZWQgYnkgdGhpcyBwcm9ncmFtLiIsIGlzX2Vycm9yPVRydWUp"
    "CiAgICAgICAgcmV0dXJuIE5vbmUKCiAgICBwb3MgPSA0CiAgICBzZXNzaW9uLnByaW1hcnlfd3Jh"
    "cCA9IHdyYXBfZnJvbV9ieXRlcyhyYXdbcG9zOnBvcyArIFdSQVBfTEVOXSk7IHBvcyArPSBXUkFQ"
    "X0xFTgogICAgc2Vzc2lvbi5yZWNvdmVyeV93cmFwID0gd3JhcF9mcm9tX2J5dGVzKHJhd1twb3M6"
    "cG9zICsgV1JBUF9MRU5dKTsgcG9zICs9IFdSQVBfTEVOCiAgICBkYXRhX25vbmNlID0gcmF3W3Bv"
    "czpwb3MgKyBJVl9MRU5dOyBwb3MgKz0gSVZfTEVOCiAgICBkYXRhX3RhZyA9IHJhd1twb3M6cG9z"
    "ICsgVEFHX0xFTl07IHBvcyArPSBUQUdfTEVOCiAgICBjaXBoZXJ0ZXh0ID0gcmF3W3BvczpdCgog"
    "ICAgd2hpY2ggPSBzaG93X2Nob2ljZV9kaWFsb2cocGFyZW50LCAiVW5sb2NrIFZhdWx0IiwgIlVu"
    "bG9jayB3aXRoIHdoaWNoIHBhc3NwaHJhc2U/IiwgIlByaW1hcnkiLCAiUmVjb3ZlcnkiKQogICAg"
    "aWYgd2hpY2ggPT0gMDoKICAgICAgICByZXR1cm4gTm9uZQogICAgcGFzc3BocmFzZSwgb2sgPSBz"
    "aG93X2lucHV0X2RpYWxvZyhwYXJlbnQsICJQYXNzcGhyYXNlIiwgIkVudGVyIHBhc3NwaHJhc2U6"
    "IiwgbWFza2VkPVRydWUpCiAgICBpZiBub3Qgb2s6CiAgICAgICAgcmV0dXJuIE5vbmUKCiAgICBy"
    "b2xlX2FhZCA9IEFBRF9ST0xFX1JFQ09WRVJZIGlmIHdoaWNoID09IDIgZWxzZSBBQURfUk9MRV9Q"
    "UklNQVJZCiAgICB3cmFwID0gc2Vzc2lvbi5yZWNvdmVyeV93cmFwIGlmIHdoaWNoID09IDIgZWxz"
    "ZSBzZXNzaW9uLnByaW1hcnlfd3JhcAogICAgdHJ5OgogICAgICAgIHNlc3Npb24uZGVrID0gdW53"
    "cmFwX2tleShwYXNzcGhyYXNlLCB3cmFwLCByb2xlX2FhZCkKICAgIGV4Y2VwdCBCQ3J5cHRFcnJv"
    "cjoKICAgICAgICBzaG93X21lc3NhZ2UocGFyZW50LCAiRmFpbGVkIiwgIldyb25nIHBhc3NwaHJh"
    "c2UgKG9yIHRoZSB2YXVsdCBpcyBjb3JydXB0ZWQpLiIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAg"
    "cmV0dXJuIE5vbmUKICAgIHRyeToKICAgICAgICBwbGFpbiA9IGFlc19nY21fZGVjcnlwdChzZXNz"
    "aW9uLmRlaywgZGF0YV9ub25jZSwgY2lwaGVydGV4dCwgZGF0YV90YWcsIEFBRF9WQVVMVF9DVFgp"
    "CiAgICBleGNlcHQgQkNyeXB0RXJyb3I6CiAgICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwgIkZh"
    "aWxlZCIsICJGYWlsZWQgdG8gZGVjcnlwdCB2YXVsdCBjb250ZW50cyAtLSBpdCBtYXkgYmUgY29y"
    "cnVwdGVkLiIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAgcmV0dXJuIE5vbmUKCiAgICB0cnk6CiAg"
    "ICAgICAgc2Vzc2lvbi5lbnRyaWVzID0ganNvbi5sb2FkcyhieXRlcyhwbGFpbikuZGVjb2RlKCJ1"
    "dGYtOCIpKQogICAgZXhjZXB0IChWYWx1ZUVycm9yLCBVbmljb2RlRGVjb2RlRXJyb3IpOgogICAg"
    "ICAgIHNlc3Npb24uZW50cmllcyA9IFtdCiAgICBmaW5hbGx5OgogICAgICAgIF96ZXJvKHBsYWlu"
    "KQogICAgc2Vzc2lvbi5tb2RpZmllZCA9IEZhbHNlCiAgICByZXR1cm4gc2Vzc2lvbgoKCmRlZiBz"
    "YXZlX3ZhdWx0X2d1aShwYXJlbnQsIHNlc3Npb24pOgogICAgcGxhaW4gPSBieXRlYXJyYXkoanNv"
    "bi5kdW1wcyhzZXNzaW9uLmVudHJpZXMpLmVuY29kZSgidXRmLTgiKSkKICAgIGRhdGFfbm9uY2Ug"
    "PSBzZWNyZXRzLnRva2VuX2J5dGVzKElWX0xFTikKICAgIHRyeToKICAgICAgICBjaXBoZXJ0ZXh0"
    "LCBkYXRhX3RhZyA9IGFlc19nY21fZW5jcnlwdChzZXNzaW9uLmRlaywgZGF0YV9ub25jZSwgYnl0"
    "ZXMocGxhaW4pLCBBQURfVkFVTFRfQ1RYKQogICAgZXhjZXB0IEJDcnlwdEVycm9yIGFzIGU6CiAg"
    "ICAgICAgc2hvd19tZXNzYWdlKHBhcmVudCwgIkVycm9yIiwgZiJGYWlsZWQgdG8gc2F2ZSB2YXVs"
    "dC5cbntlfSIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAgcmV0dXJuCiAgICBmaW5hbGx5OgogICAg"
    "ICAgIF96ZXJvKHBsYWluKQogICAgdHJ5OgogICAgICAgIHdpdGggb3BlbihzZXNzaW9uLnBhdGgs"
    "ICJ3YiIpIGFzIGY6CiAgICAgICAgICAgIGYud3JpdGUoVkFVTFRfTUFHSUMpCiAgICAgICAgICAg"
    "IGYud3JpdGUod3JhcF90b19ieXRlcyhzZXNzaW9uLnByaW1hcnlfd3JhcCkpCiAgICAgICAgICAg"
    "IGYud3JpdGUod3JhcF90b19ieXRlcyhzZXNzaW9uLnJlY292ZXJ5X3dyYXApKQogICAgICAgICAg"
    "ICBmLndyaXRlKGRhdGFfbm9uY2UpCiAgICAgICAgICAgIGYud3JpdGUoZGF0YV90YWcpCiAgICAg"
    "ICAgICAgIGYud3JpdGUoY2lwaGVydGV4dCkKICAgIGV4Y2VwdCBPU0Vycm9yIGFzIGU6CiAgICAg"
    "ICAgc2hvd19tZXNzYWdlKHBhcmVudCwgIkVycm9yIiwgZiJGYWlsZWQgdG8gc2F2ZSB2YXVsdC5c"
    "bntlfSIsIGlzX2Vycm9yPVRydWUpCiAgICAgICAgcmV0dXJuCiAgICBzZXNzaW9uLm1vZGlmaWVk"
    "ID0gRmFsc2UKICAgIHNob3dfbWVzc2FnZShwYXJlbnQsICJTYXZlZCIsIGYiVmF1bHQgc2F2ZWQg"
    "dG86XG57c2Vzc2lvbi5wYXRofSIpCgoKY2xhc3MgVmF1bHRXaW5kb3codGsuVG9wbGV2ZWwpOgog"
    "ICAgSEVBREVSX0ggPSA2OAoKICAgIGRlZiBfX2luaXRfXyhzZWxmLCBwYXJlbnQsIHNlc3Npb24p"
    "OgogICAgICAgIHN1cGVyKCkuX19pbml0X18ocGFyZW50KQogICAgICAgIHNlbGYuc2Vzc2lvbiA9"
    "IHNlc3Npb24KICAgICAgICBzZWxmLnRpdGxlKCJQYXNzd29yZCBWYXVsdCIpCiAgICAgICAgc2Vs"
    "Zi5jb25maWd1cmUoYmc9Qk9EWV9DT0xPUikKICAgICAgICBzZWxmLnJlc2l6YWJsZShGYWxzZSwg"
    "RmFsc2UpCiAgICAgICAgc2VsZi50cmFuc2llbnQocGFyZW50KQogICAgICAgIHdpZHRoLCBoZWln"
    "aHQgPSA1ODAsIDUyMAogICAgICAgIGFwcGx5X2RhcmtfdGl0bGViYXIoc2VsZikKCiAgICAgICAg"
    "aGVhZGVyID0gdGsuQ2FudmFzKHNlbGYsIHdpZHRoPXdpZHRoLCBoZWlnaHQ9c2VsZi5IRUFERVJf"
    "SCwgYmc9QUNDRU5UX0NPTE9SLCBoaWdobGlnaHR0aGlja25lc3M9MCkKICAgICAgICBoZWFkZXIu"
    "cGxhY2UoeD0wLCB5PTApCiAgICAgICAgZHJhd192ZXJ0aWNhbF9ncmFkaWVudChoZWFkZXIsIDAs"
    "IDAsIHdpZHRoLCBzZWxmLkhFQURFUl9ILCBhZGp1c3RfYnJpZ2h0bmVzcyhBQ0NFTlRfQ09MT1Is"
    "IDE0KSwgQUNDRU5UX0NPTE9SKQogICAgICAgIGhlYWRlci5jcmVhdGVfbGluZSgwLCBzZWxmLkhF"
    "QURFUl9IIC0gMSwgd2lkdGgsIHNlbGYuSEVBREVSX0ggLSAxLCBmaWxsPUJPUkRFUl9DT0xPUikK"
    "ICAgICAgICBoZWFkZXIuY3JlYXRlX3RleHQoTUFSR0lOLCBzZWxmLkhFQURFUl9IIC8vIDIsIHRl"
    "eHQ9IlBhc3N3b3JkIFZhdWx0IiwgYW5jaG9yPSJ3IiwgZmlsbD0iI2ZmZmZmZiIsIGZvbnQ9Rk9O"
    "VF9USVRMRSkKCiAgICAgICAgYm9keSA9IHRrLkZyYW1lKHNlbGYsIGJnPUJPRFlfQ09MT1IpCiAg"
    "ICAgICAgYm9keS5wbGFjZSh4PTAsIHk9c2VsZi5IRUFERVJfSCwgd2lkdGg9d2lkdGgsIGhlaWdo"
    "dD1oZWlnaHQgLSBzZWxmLkhFQURFUl9IKQoKICAgICAgICBzZWxmLnN0YXR1c19sYWJlbCA9IHRr"
    "LkxhYmVsKGJvZHksIGJnPUJPRFlfQ09MT1IsIGZnPUFDQ0VOVF9TVUJURVhULCBmb250PUZPTlRf"
    "Tk9STUFMLCBhbmNob3I9InciKQogICAgICAgIHNlbGYuc3RhdHVzX2xhYmVsLnBhY2soZmlsbD0i"
    "eCIsIHBhZHg9TUFSR0lOLCBwYWR5PSgxNCwgOCkpCgogICAgICAgIHN0eWxlID0gdHRrLlN0eWxl"
    "KHNlbGYpCiAgICAgICAgc3R5bGUudGhlbWVfdXNlKCJjbGFtIikKICAgICAgICBzdHlsZS5jb25m"
    "aWd1cmUoIlZhdWx0LlRyZWV2aWV3IiwgYmFja2dyb3VuZD1FRElUX0JHX0NPTE9SLCBmaWVsZGJh"
    "Y2tncm91bmQ9RURJVF9CR19DT0xPUiwKICAgICAgICAgICAgICAgICAgICAgICAgZm9yZWdyb3Vu"
    "ZD1URVhUX0NPTE9SLCByb3doZWlnaHQ9MjQsIGJvcmRlcndpZHRoPTAsIGZvbnQ9Rk9OVF9OT1JN"
    "QUwpCiAgICAgICAgc3R5bGUuY29uZmlndXJlKCJWYXVsdC5UcmVldmlldy5IZWFkaW5nIiwgYmFj"
    "a2dyb3VuZD1BQ0NFTlRfQ09MT1IsIGZvcmVncm91bmQ9VEVYVF9DT0xPUiwgcmVsaWVmPSJmbGF0"
    "IiwgZm9udD1GT05UX05PUk1BTCkKICAgICAgICBzdHlsZS5tYXAoIlZhdWx0LlRyZWV2aWV3Iiwg"
    "YmFja2dyb3VuZD1bKCJzZWxlY3RlZCIsIEJUTl9QUklNQVJZX0JHKV0sIGZvcmVncm91bmQ9Wygi"
    "c2VsZWN0ZWQiLCAiI2ZmZmZmZiIpXSkKICAgICAgICBzdHlsZS5tYXAoIlZhdWx0LlRyZWV2aWV3"
    "LkhlYWRpbmciLCBiYWNrZ3JvdW5kPVsoImFjdGl2ZSIsIEFDQ0VOVF9DT0xPUildKQoKICAgICAg"
    "ICBsaXN0X2ZyYW1lID0gdGsuRnJhbWUoYm9keSwgYmc9Qk9SREVSX0NPTE9SKQogICAgICAgIGxp"
    "c3RfZnJhbWUucGFjayhmaWxsPSJib3RoIiwgZXhwYW5kPVRydWUsIHBhZHg9TUFSR0lOLCBwYWR5"
    "PSgwLCAxMCkpCiAgICAgICAgc2VsZi50cmVlID0gdHRrLlRyZWV2aWV3KGxpc3RfZnJhbWUsIGNv"
    "bHVtbnM9KCJzaXRlIiwgInVzZXIiKSwgc2hvdz0iaGVhZGluZ3MiLCBzdHlsZT0iVmF1bHQuVHJl"
    "ZXZpZXciLCBzZWxlY3Rtb2RlPSJicm93c2UiLCBoZWlnaHQ9MTApCiAgICAgICAgc2VsZi50cmVl"
    "LmhlYWRpbmcoInNpdGUiLCB0ZXh0PSJTaXRlIC8gU2VydmljZSIpCiAgICAgICAgc2VsZi50cmVl"
    "LmhlYWRpbmcoInVzZXIiLCB0ZXh0PSJVc2VybmFtZSIpCiAgICAgICAgc2VsZi50cmVlLmNvbHVt"
    "bigic2l0ZSIsIHdpZHRoPTMxMCkKICAgICAgICBzZWxmLnRyZWUuY29sdW1uKCJ1c2VyIiwgd2lk"
    "dGg9MjMwKQogICAgICAgIHNlbGYudHJlZS5wYWNrKGZpbGw9ImJvdGgiLCBleHBhbmQ9VHJ1ZSwg"
    "cGFkeD0xLCBwYWR5PTEpCiAgICAgICAgc2VsZi50cmVlLmJpbmQoIjxEb3VibGUtMT4iLCBsYW1i"
    "ZGEgZTogc2VsZi52aWV3X2VudHJ5KCkpCgogICAgICAgIHJvdzEgPSB0ay5GcmFtZShib2R5LCBi"
    "Zz1CT0RZX0NPTE9SKQogICAgICAgIHJvdzEucGFjayhmaWxsPSJ4IiwgcGFkeD1NQVJHSU4sIHBh"
    "ZHk9KDAsIDgpKQogICAgICAgIFJvdW5kZWRCdXR0b24ocm93MSwgIkFkZCIsIGNvbW1hbmQ9c2Vs"
    "Zi5hZGRfZW50cnksIHdpZHRoPTEyMiwgaGVpZ2h0PTMwKS5wYWNrKHNpZGU9ImxlZnQiLCBwYWR4"
    "PSgwLCAxMCkpCiAgICAgICAgUm91bmRlZEJ1dHRvbihyb3cxLCAiVmlldyIsIGNvbW1hbmQ9c2Vs"
    "Zi52aWV3X2VudHJ5LCB3aWR0aD0xMjIsIGhlaWdodD0zMCkucGFjayhzaWRlPSJsZWZ0IiwgcGFk"
    "eD0oMCwgMTApKQogICAgICAgIFJvdW5kZWRCdXR0b24ocm93MSwgIkVkaXQiLCBjb21tYW5kPXNl"
    "bGYuZWRpdF9lbnRyeSwgd2lkdGg9MTIyLCBoZWlnaHQ9MzApLnBhY2soc2lkZT0ibGVmdCIsIHBh"
    "ZHg9KDAsIDEwKSkKICAgICAgICBSb3VuZGVkQnV0dG9uKHJvdzEsICJEZWxldGUiLCBjb21tYW5k"
    "PXNlbGYuZGVsZXRlX2VudHJ5LCB3aWR0aD0xMjIsIGhlaWdodD0zMCkucGFjayhzaWRlPSJsZWZ0"
    "IikKCiAgICAgICAgcm93MiA9IHRrLkZyYW1lKGJvZHksIGJnPUJPRFlfQ09MT1IpCiAgICAgICAg"
    "cm93Mi5wYWNrKGZpbGw9IngiLCBwYWR4PU1BUkdJTiwgcGFkeT0oMCwgTUFSR0lOKSkKICAgICAg"
    "ICBSb3VuZGVkQnV0dG9uKHJvdzIsICJTYXZlIFZhdWx0IiwgY29tbWFuZD1zZWxmLnNhdmUsIHdp"
    "ZHRoPTE1MCwgaGVpZ2h0PTMwLCBwcmltYXJ5PVRydWUpLnBhY2soc2lkZT0ibGVmdCIsIHBhZHg9"
    "KDAsIDEwKSkKICAgICAgICBSb3VuZGVkQnV0dG9uKHJvdzIsICJDaGFuZ2UgUGFzc3BocmFzZXMi"
    "LCBjb21tYW5kPXNlbGYuY2hhbmdlX3Bhc3NwaHJhc2VzLCB3aWR0aD0yMDAsIGhlaWdodD0zMCku"
    "cGFjayhzaWRlPSJsZWZ0IiwgcGFkeD0oMCwgMTApKQogICAgICAgIFJvdW5kZWRCdXR0b24ocm93"
    "MiwgIkNsb3NlIiwgY29tbWFuZD1zZWxmLm9uX2Nsb3NlLCB3aWR0aD0xNDgsIGhlaWdodD0zMCku"
    "cGFjayhzaWRlPSJsZWZ0IikKCiAgICAgICAgc2VsZi5wcm90b2NvbCgiV01fREVMRVRFX1dJTkRP"
    "VyIsIHNlbGYub25fY2xvc2UpCiAgICAgICAgc2VsZi5yZWZyZXNoX2xpc3QoKQogICAgICAgIHNl"
    "bGYudXBkYXRlX3N0YXR1cygpCiAgICAgICAgY2VudGVyX3dpbmRvdyhzZWxmLCBwYXJlbnQsIHdp"
    "ZHRoLCBoZWlnaHQpCiAgICAgICAgc2VsZi5ncmFiX3NldCgpCgogICAgZGVmIHJlZnJlc2hfbGlz"
    "dChzZWxmKToKICAgICAgICBzZWxmLnRyZWUuZGVsZXRlKCpzZWxmLnRyZWUuZ2V0X2NoaWxkcmVu"
    "KCkpCiAgICAgICAgZm9yIGksIGUgaW4gZW51bWVyYXRlKHNlbGYuc2Vzc2lvbi5lbnRyaWVzKToK"
    "ICAgICAgICAgICAgc2VsZi50cmVlLmluc2VydCgiIiwgImVuZCIsIGlpZD1zdHIoaSksIHZhbHVl"
    "cz0oZVsic2l0ZSJdLCBlWyJ1c2VybmFtZSJdKSkKCiAgICBkZWYgdXBkYXRlX3N0YXR1cyhzZWxm"
    "KToKICAgICAgICBzdGF0ZSA9ICIgICp1bnNhdmVkIGNoYW5nZXMqIiBpZiBzZWxmLnNlc3Npb24u"
    "bW9kaWZpZWQgZWxzZSAiICAoc2F2ZWQpIgogICAgICAgIHNlbGYuc3RhdHVzX2xhYmVsLmNvbmZp"
    "Z3VyZSh0ZXh0PWYiVmF1bHQ6ICB7c2VsZi5zZXNzaW9uLnBhdGh9e3N0YXRlfSIpCgogICAgZGVm"
    "IHNlbGVjdGVkX2luZGV4KHNlbGYpOgogICAgICAgIHNlbCA9IHNlbGYudHJlZS5zZWxlY3Rpb24o"
    "KQogICAgICAgIGlmIG5vdCBzZWw6CiAgICAgICAgICAgIHNob3dfbWVzc2FnZShzZWxmLCAiTm8g"
    "c2VsZWN0aW9uIiwgIlNlbGVjdCBhbiBlbnRyeSBmaXJzdC4iLCBpc19lcnJvcj1UcnVlKQogICAg"
    "ICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIHJldHVybiBpbnQoc2VsWzBdKQoKICAgIGRlZiBh"
    "ZGRfZW50cnkoc2VsZik6CiAgICAgICAgc2l0ZSwgb2sgPSBzaG93X2lucHV0X2RpYWxvZyhzZWxm"
    "LCAiQWRkIEVudHJ5IiwgIlNpdGUvc2VydmljZSBuYW1lOiIpCiAgICAgICAgaWYgbm90IG9rIG9y"
    "IG5vdCBzaXRlOgogICAgICAgICAgICByZXR1cm4KICAgICAgICB1c2VybmFtZSwgb2sgPSBzaG93"
    "X2lucHV0X2RpYWxvZyhzZWxmLCAiQWRkIEVudHJ5IiwgIlVzZXJuYW1lL2VtYWlsOiIpCiAgICAg"
    "ICAgaWYgbm90IG9rOgogICAgICAgICAgICByZXR1cm4KICAgICAgICBjaG9pY2UgPSBzaG93X2No"
    "b2ljZV9kaWFsb2coc2VsZiwgIlBhc3N3b3JkIiwgIkdlbmVyYXRlIGEgc3Ryb25nIHBhc3N3b3Jk"
    "LCBvciBlbnRlciB5b3VyIG93bj8iLCAiR2VuZXJhdGUiLCAiRW50ZXIgbXkgb3duIikKICAgICAg"
    "ICBpZiBjaG9pY2UgPT0gMDoKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgaWYgY2hvaWNlID09"
    "IDE6CiAgICAgICAgICAgIHBhc3N3b3JkID0gZ2VuZXJhdGVfc2l0ZV9wYXNzd29yZCgpCiAgICAg"
    "ICAgICAgIHNob3dfY29weWFibGVfZGlhbG9nKHNlbGYsICJHZW5lcmF0ZWQgcGFzc3dvcmQiLCBm"
    "IkdlbmVyYXRlZCBwYXNzd29yZCBmb3Ige3NpdGV9OiIsIHBhc3N3b3JkLCBGYWxzZSkKICAgICAg"
    "ICBlbHNlOgogICAgICAgICAgICBwYXNzd29yZCwgb2sgPSBzaG93X2lucHV0X2RpYWxvZyhzZWxm"
    "LCAiUGFzc3dvcmQiLCAiRW50ZXIgcGFzc3dvcmQ6IiwgbWFza2VkPVRydWUpCiAgICAgICAgICAg"
    "IGlmIG5vdCBvazoKICAgICAgICAgICAgICAgIHJldHVybgogICAgICAgIG5vdGVzLCBvayA9IHNo"
    "b3dfaW5wdXRfZGlhbG9nKHNlbGYsICJOb3RlcyIsICJOb3RlcyAob3B0aW9uYWwpOiIpCiAgICAg"
    "ICAgc2VsZi5zZXNzaW9uLmVudHJpZXMuYXBwZW5kKHsic2l0ZSI6IHNpdGUsICJ1c2VybmFtZSI6"
    "IHVzZXJuYW1lLCAicGFzc3dvcmQiOiBwYXNzd29yZCwgIm5vdGVzIjogbm90ZXMgaWYgb2sgZWxz"
    "ZSAiIn0pCiAgICAgICAgc2VsZi5zZXNzaW9uLm1vZGlmaWVkID0gVHJ1ZQogICAgICAgIHNlbGYu"
    "cmVmcmVzaF9saXN0KCkKICAgICAgICBzZWxmLnVwZGF0ZV9zdGF0dXMoKQoKICAgIGRlZiB2aWV3"
    "X2VudHJ5KHNlbGYpOgogICAgICAgIGlkeCA9IHNlbGYuc2VsZWN0ZWRfaW5kZXgoKQogICAgICAg"
    "IGlmIGlkeCBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4KICAgICAgICBlID0gc2VsZi5zZXNz"
    "aW9uLmVudHJpZXNbaWR4XQogICAgICAgIG1zZyA9IGYiU2l0ZToge2VbJ3NpdGUnXX1cblVzZXJu"
    "YW1lOiB7ZVsndXNlcm5hbWUnXX1cblBhc3N3b3JkOiB7ZVsncGFzc3dvcmQnXX0iCiAgICAgICAg"
    "aWYgZS5nZXQoIm5vdGVzIik6CiAgICAgICAgICAgIG1zZyArPSBmIlxuTm90ZXM6IHtlWydub3Rl"
    "cyddfSIKICAgICAgICBzaG93X2NvcHlhYmxlX2RpYWxvZyhzZWxmLCAiRW50cnkgRGV0YWlscyIs"
    "ICJEZXRhaWxzIChyZWFkLW9ubHkpOiIsIG1zZywgVHJ1ZSkKCiAgICBkZWYgZWRpdF9lbnRyeShz"
    "ZWxmKToKICAgICAgICBpZHggPSBzZWxmLnNlbGVjdGVkX2luZGV4KCkKICAgICAgICBpZiBpZHgg"
    "aXMgTm9uZToKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgZSA9IHNlbGYuc2Vzc2lvbi5lbnRy"
    "aWVzW2lkeF0KICAgICAgICBuZXdfc2l0ZSwgb2sgPSBzaG93X2lucHV0X2RpYWxvZyhzZWxmLCAi"
    "RWRpdCBFbnRyeSIsICJTaXRlIG5hbWU6IiwgZGVmYXVsdD1lWyJzaXRlIl0pCiAgICAgICAgaWYg"
    "b2sgYW5kIG5ld19zaXRlOgogICAgICAgICAgICBlWyJzaXRlIl0gPSBuZXdfc2l0ZQogICAgICAg"
    "IG5ld191c2VyLCBvayA9IHNob3dfaW5wdXRfZGlhbG9nKHNlbGYsICJFZGl0IEVudHJ5IiwgIlVz"
    "ZXJuYW1lOiIsIGRlZmF1bHQ9ZVsidXNlcm5hbWUiXSkKICAgICAgICBpZiBvazoKICAgICAgICAg"
    "ICAgZVsidXNlcm5hbWUiXSA9IG5ld191c2VyCiAgICAgICAgY2hvaWNlID0gc2hvd19jaG9pY2Vf"
    "ZGlhbG9nKHNlbGYsICJQYXNzd29yZCIsICJDaGFuZ2UgdGhlIHBhc3N3b3JkPyIsICJHZW5lcmF0"
    "ZSBuZXciLCAiRW50ZXIgbmV3IikKICAgICAgICBpZiBjaG9pY2UgPT0gMToKICAgICAgICAgICAg"
    "ZVsicGFzc3dvcmQiXSA9IGdlbmVyYXRlX3NpdGVfcGFzc3dvcmQoKQogICAgICAgICAgICBzaG93"
    "X2NvcHlhYmxlX2RpYWxvZyhzZWxmLCAiR2VuZXJhdGVkIHBhc3N3b3JkIiwgIk5ldyBnZW5lcmF0"
    "ZWQgcGFzc3dvcmQ6IiwgZVsicGFzc3dvcmQiXSwgRmFsc2UpCiAgICAgICAgZWxpZiBjaG9pY2Ug"
    "PT0gMjoKICAgICAgICAgICAgbmV3X3Bhc3MsIG9rID0gc2hvd19pbnB1dF9kaWFsb2coc2VsZiwg"
    "IlBhc3N3b3JkIiwgIkVudGVyIG5ldyBwYXNzd29yZDoiLCBtYXNrZWQ9VHJ1ZSkKICAgICAgICAg"
    "ICAgaWYgb2sgYW5kIG5ld19wYXNzOgogICAgICAgICAgICAgICAgZVsicGFzc3dvcmQiXSA9IG5l"
    "d19wYXNzCiAgICAgICAgbmV3X25vdGVzLCBvayA9IHNob3dfaW5wdXRfZGlhbG9nKHNlbGYsICJF"
    "ZGl0IEVudHJ5IiwgIk5vdGVzOiIsIGRlZmF1bHQ9ZS5nZXQoIm5vdGVzIiwgIiIpKQogICAgICAg"
    "IGlmIG9rOgogICAgICAgICAgICBlWyJub3RlcyJdID0gbmV3X25vdGVzCiAgICAgICAgc2VsZi5z"
    "ZXNzaW9uLm1vZGlmaWVkID0gVHJ1ZQogICAgICAgIHNlbGYucmVmcmVzaF9saXN0KCkKICAgICAg"
    "ICBzZWxmLnVwZGF0ZV9zdGF0dXMoKQoKICAgIGRlZiBkZWxldGVfZW50cnkoc2VsZik6CiAgICAg"
    "ICAgaWR4ID0gc2VsZi5zZWxlY3RlZF9pbmRleCgpCiAgICAgICAgaWYgaWR4IGlzIE5vbmU6CiAg"
    "ICAgICAgICAgIHJldHVybgogICAgICAgIHNpdGUgPSBzZWxmLnNlc3Npb24uZW50cmllc1tpZHhd"
    "WyJzaXRlIl0KICAgICAgICBjb25maXJtID0gc2hvd19jaG9pY2VfZGlhbG9nKHNlbGYsICJDb25m"
    "aXJtIERlbGV0ZSIsIGYiRGVsZXRlICd7c2l0ZX0nPyIsICJZZXMsIGRlbGV0ZSIsICJDYW5jZWwi"
    "KQogICAgICAgIGlmIGNvbmZpcm0gPT0gMToKICAgICAgICAgICAgZGVsIHNlbGYuc2Vzc2lvbi5l"
    "bnRyaWVzW2lkeF0KICAgICAgICAgICAgc2VsZi5zZXNzaW9uLm1vZGlmaWVkID0gVHJ1ZQogICAg"
    "ICAgICAgICBzZWxmLnJlZnJlc2hfbGlzdCgpCiAgICAgICAgICAgIHNlbGYudXBkYXRlX3N0YXR1"
    "cygpCgogICAgZGVmIGNoYW5nZV9wYXNzcGhyYXNlcyhzZWxmKToKICAgICAgICBuZXdfcHJpbWFy"
    "eSA9IG9idGFpbl9wYXNzcGhyYXNlX2d1aShzZWxmLCAibmV3IHByaW1hcnkiKQogICAgICAgIGlm"
    "IG5vdCBuZXdfcHJpbWFyeToKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgbmV3X3JlY292ZXJ5"
    "ID0gb2J0YWluX3Bhc3NwaHJhc2VfZ3VpKHNlbGYsICJuZXcgcmVjb3ZlcnkiKQogICAgICAgIGlm"
    "IG5vdCBuZXdfcmVjb3Zlcnk6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIHRyeToKICAgICAg"
    "ICAgICAgc2VsZi5zZXNzaW9uLnByaW1hcnlfd3JhcCA9IHdyYXBfa2V5KG5ld19wcmltYXJ5LCBz"
    "ZWxmLnNlc3Npb24uZGVrLCBBQURfUk9MRV9QUklNQVJZKQogICAgICAgICAgICBzZWxmLnNlc3Np"
    "b24ucmVjb3Zlcnlfd3JhcCA9IHdyYXBfa2V5KG5ld19yZWNvdmVyeSwgc2VsZi5zZXNzaW9uLmRl"
    "aywgQUFEX1JPTEVfUkVDT1ZFUlkpCiAgICAgICAgZXhjZXB0IEJDcnlwdEVycm9yIGFzIGU6CiAg"
    "ICAgICAgICAgIHNob3dfbWVzc2FnZShzZWxmLCAiRXJyb3IiLCBmIkZhaWxlZCB0byB1cGRhdGUg"
    "cGFzc3BocmFzZXMuXG57ZX0iLCBpc19lcnJvcj1UcnVlKQogICAgICAgICAgICByZXR1cm4KICAg"
    "ICAgICBzZWxmLnNlc3Npb24ubW9kaWZpZWQgPSBUcnVlCiAgICAgICAgc2VsZi51cGRhdGVfc3Rh"
    "dHVzKCkKICAgICAgICBzaG93X21lc3NhZ2Uoc2VsZiwgIlVwZGF0ZWQiLCAiUGFzc3BocmFzZXMg"
    "dXBkYXRlZCBpbiBtZW1vcnkuIENsaWNrIFNhdmUgdG8gbWFrZSB0aGlzIHBlcm1hbmVudC4iKQoK"
    "ICAgIGRlZiBzYXZlKHNlbGYpOgogICAgICAgIHNhdmVfdmF1bHRfZ3VpKHNlbGYsIHNlbGYuc2Vz"
    "c2lvbikKICAgICAgICBzZWxmLnVwZGF0ZV9zdGF0dXMoKQoKICAgIGRlZiBvbl9jbG9zZShzZWxm"
    "KToKICAgICAgICBpZiBzZWxmLnNlc3Npb24ubW9kaWZpZWQ6CiAgICAgICAgICAgIGNob2ljZSA9"
    "IHNob3dfY2hvaWNlX2RpYWxvZyhzZWxmLCAiVW5zYXZlZCBDaGFuZ2VzIiwgIllvdSBoYXZlIHVu"
    "c2F2ZWQgY2hhbmdlcy5cblNhdmUgYmVmb3JlIGNsb3Npbmc/IiwgIlNhdmUiLCAiRGlzY2FyZCIp"
    "CiAgICAgICAgICAgIGlmIGNob2ljZSA9PSAxOgogICAgICAgICAgICAgICAgc2F2ZV92YXVsdF9n"
    "dWkoc2VsZiwgc2VsZi5zZXNzaW9uKQogICAgICAgIHNlbGYuc2Vzc2lvbi53aXBlKCkKICAgICAg"
    "ICBzZWxmLmdyYWJfcmVsZWFzZSgpCiAgICAgICAgc2VsZi5kZXN0cm95KCkKCgojID09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PQojICBNYWluIHdpbmRvdwojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
    "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKY2xhc3MgTWFpbkFwcCh0ay5Uayk6"
    "CiAgICBIRUFERVJfSCA9IDk2CgogICAgZGVmIF9faW5pdF9fKHNlbGYpOgogICAgICAgIHN1cGVy"
    "KCkuX19pbml0X18oKQogICAgICAgIHNlbGYudGl0bGUoIkVuY3J5cHRlciIpCiAgICAgICAgc2Vs"
    "Zi5jb25maWd1cmUoYmc9Qk9EWV9DT0xPUikKICAgICAgICBzZWxmLnJlc2l6YWJsZShGYWxzZSwg"
    "RmFsc2UpCiAgICAgICAgd2lkdGgsIGhlaWdodCA9IDMwMCwgNTAwCiAgICAgICAgc2VsZi5nZW9t"
    "ZXRyeShmInt3aWR0aH14e2hlaWdodH0iKQogICAgICAgIGFwcGx5X2RhcmtfdGl0bGViYXIoc2Vs"
    "ZikKCiAgICAgICAgaGVhZGVyID0gdGsuQ2FudmFzKHNlbGYsIHdpZHRoPXdpZHRoLCBoZWlnaHQ9"
    "c2VsZi5IRUFERVJfSCwgYmc9QUNDRU5UX0NPTE9SLCBoaWdobGlnaHR0aGlja25lc3M9MCkKICAg"
    "ICAgICBoZWFkZXIucGxhY2UoeD0wLCB5PTApCiAgICAgICAgZHJhd192ZXJ0aWNhbF9ncmFkaWVu"
    "dChoZWFkZXIsIDAsIDAsIHdpZHRoLCBzZWxmLkhFQURFUl9ILCBhZGp1c3RfYnJpZ2h0bmVzcyhB"
    "Q0NFTlRfQ09MT1IsIDE0KSwgQUNDRU5UX0NPTE9SKQogICAgICAgIGhlYWRlci5jcmVhdGVfbGlu"
    "ZSgwLCBzZWxmLkhFQURFUl9IIC0gMSwgd2lkdGgsIHNlbGYuSEVBREVSX0ggLSAxLCBmaWxsPUJP"
    "UkRFUl9DT0xPUikKICAgICAgICBoZWFkZXIuY3JlYXRlX3RleHQoTUFSR0lOLCAzMCwgdGV4dD0i"
    "RW5jcnlwdGVyIiwgYW5jaG9yPSJ3IiwgZmlsbD0iI2ZmZmZmZiIsIGZvbnQ9Rk9OVF9USVRMRSkK"
    "ICAgICAgICBoZWFkZXIuY3JlYXRlX3RleHQoTUFSR0lOLCA2MCwgdGV4dD0iRW5jcnlwdCBhbnkg"
    "ZmlsZSB0eXBlLCB0ZXh0LCIsIGFuY2hvcj0idyIsIGZpbGw9QUNDRU5UX1NVQlRFWFQsIGZvbnQ9"
    "Rk9OVF9TVUJUSVRMRSkKICAgICAgICBoZWFkZXIuY3JlYXRlX3RleHQoTUFSR0lOLCA3OCwgdGV4"
    "dD0ib3IgbWFuYWdlIHlvdXIgdmF1bHQuIiwgYW5jaG9yPSJ3IiwgZmlsbD1BQ0NFTlRfU1VCVEVY"
    "VCwgZm9udD1GT05UX1NVQlRJVExFKQoKICAgICAgICBib2R5ID0gdGsuRnJhbWUoc2VsZiwgYmc9"
    "Qk9EWV9DT0xPUikKICAgICAgICBib2R5LnBsYWNlKHg9MCwgeT1zZWxmLkhFQURFUl9ILCB3aWR0"
    "aD13aWR0aCwgaGVpZ2h0PWhlaWdodCAtIHNlbGYuSEVBREVSX0gpCgogICAgICAgIGJ1dHRvbnMg"
    "PSBbCiAgICAgICAgICAgICgiRW5jcnlwdCBUZXh0Iiwgc2VsZi5lbmNyeXB0X3RleHQsIEZhbHNl"
    "KSwKICAgICAgICAgICAgKCJEZWNyeXB0IFRleHQiLCBzZWxmLmRlY3J5cHRfdGV4dCwgRmFsc2Up"
    "LAogICAgICAgICAgICAoIkVuY3J5cHQgRmlsZSIsIHNlbGYuZW5jcnlwdF9maWxlLCBGYWxzZSks"
    "CiAgICAgICAgICAgICgiRGVjcnlwdCBGaWxlIiwgc2VsZi5kZWNyeXB0X2ZpbGUsIEZhbHNlKSwK"
    "ICAgICAgICAgICAgKCJQYXNzd29yZCBWYXVsdCIsIHNlbGYub3Blbl92YXVsdCwgVHJ1ZSksCiAg"
    "ICAgICAgICAgICgiRXhpdCIsIHNlbGYuZGVzdHJveSwgRmFsc2UpLAogICAgICAgIF0KICAgICAg"
    "ICB5ID0gMTYKICAgICAgICBmb3IgdGV4dCwgY21kLCBwcmltYXJ5IGluIGJ1dHRvbnM6CiAgICAg"
    "ICAgICAgIFJvdW5kZWRCdXR0b24oYm9keSwgdGV4dCwgY29tbWFuZD1jbWQsIHdpZHRoPTI2MCwg"
    "aGVpZ2h0PTQwLCBwcmltYXJ5PXByaW1hcnkpLnBsYWNlKHg9TUFSR0lOLCB5PXkpCiAgICAgICAg"
    "ICAgIHkgKz0gNDAgKyAxMgogICAgICAgICAgICBpZiB0ZXh0ID09ICJQYXNzd29yZCBWYXVsdCI6"
    "CiAgICAgICAgICAgICAgICB5ICs9IDEwCgogICAgZGVmIGVuY3J5cHRfdGV4dChzZWxmKToKICAg"
    "ICAgICBkb19lbmNyeXB0X3RleHQoc2VsZikKCiAgICBkZWYgZGVjcnlwdF90ZXh0KHNlbGYpOgog"
    "ICAgICAgIGRvX2RlY3J5cHRfdGV4dChzZWxmKQoKICAgIGRlZiBlbmNyeXB0X2ZpbGUoc2VsZik6"
    "CiAgICAgICAgZG9fZW5jcnlwdF9maWxlKHNlbGYpCgogICAgZGVmIGRlY3J5cHRfZmlsZShzZWxm"
    "KToKICAgICAgICBkb19kZWNyeXB0X2ZpbGUoc2VsZikKCiAgICBkZWYgb3Blbl92YXVsdChzZWxm"
    "KToKICAgICAgICBzZXNzaW9uID0gb3Blbl9vcl9jcmVhdGVfdmF1bHRfZ3VpKHNlbGYpCiAgICAg"
    "ICAgaWYgc2Vzc2lvbiBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4KICAgICAgICB2YXVsdF93"
    "aW4gPSBWYXVsdFdpbmRvdyhzZWxmLCBzZXNzaW9uKQogICAgICAgIHNlbGYud2FpdF93aW5kb3co"
    "dmF1bHRfd2luKQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBNYWluQXBwKCkubWFp"
    "bmxvb3AoKQo="
))
REQUIREMENTS_TXT = (
    "cryptography>=41\n"
    "# Add any other packages the app needs here, one per line, e.g.:\n"
    "# somepackage==1.2.3\n"
)

CREATE_SHORTCUT_PS1 = (
    'param(\n'
    '    [Parameter(Mandatory=$true)][string]$Target,\n'
    '    [string]$Arguments = "",\n'
    '    [string]$WorkingDirectory = "",\n'
    '    [string]$ShortcutName = "Encrypter"\n'
    ')\n'
    '$desktop = [Environment]::GetFolderPath("Desktop")\n'
    '$shell = New-Object -ComObject WScript.Shell\n'
    '$shortcut = $shell.CreateShortcut((Join-Path $desktop "$ShortcutName.lnk"))\n'
    '$shortcut.TargetPath = $Target\n'
    '$shortcut.Arguments = $Arguments\n'
    '$shortcut.WorkingDirectory = $WorkingDirectory\n'
    '$shortcut.Save()\n'
    'Write-Host "Shortcut created: $desktop\\$ShortcutName.lnk"\n'
)

LINUX_DESKTOP_ENTRY = (
    "[Desktop Entry]\n"
    "Type=Application\n"
    "Name=Encrypter\n"
    "Comment=Encrypt text and files, and manage a password vault\n"
    "Exec={exec_cmd}\n"
    "Path={workdir}\n"
    "Terminal=false\n"
    "Categories=Utility;Security;\n"
)

MACOS_LAUNCHER_COMMAND = (
    "#!/bin/bash\n"
    'cd "{workdir}"\n'
    "exec {exec_cmd}\n"
)

ACCENT_COLOR = "#121318"
ACCENT_SUBTEXT = "#8c94a8"
BODY_COLOR = "#1c1e24"
EDIT_BG_COLOR = "#14161b"
TEXT_COLOR = "#e6e8ed"
BORDER_COLOR = "#3c404a"
BTN_BG = "#2a2d36"
BTN_BG_HOVER = "#383c48"
BTN_PRIMARY_BG = "#4a66d6"
BTN_PRIMARY_BG_HOVER = "#5c78e6"


def apply_dark_titlebar(window):
    """Windows-only cosmetic touch; no-op elsewhere (macOS follows the system
    appearance automatically, and most Linux window managers don't expose an
    equivalent per-window API)."""
    if sys.platform != "win32":
        return
    try:
        window.update_idletasks()
        hwnd = ctypes.windll.user32.GetParent(window.winfo_id())
        dwmapi = ctypes.windll.dwmapi
        value = ctypes.c_int(1)
        for attr in (20, 19):
            hr = dwmapi.DwmSetWindowAttribute(hwnd, attr, ctypes.byref(value), ctypes.sizeof(value))
            if hr == 0:
                break
    except Exception:
        pass


import ctypes


def find_python():
    candidates = ("py", "python3", "python") if sys.platform == "win32" else ("python3", "python")
    for candidate in candidates:
        p = shutil.which(candidate)
        if p:
            return p
    return None


def default_install_dir(sysinfo):
    if sysinfo["family"] == "windows":
        base = os.environ.get("LOCALAPPDATA", os.path.expanduser("~"))
        return os.path.join(base, "Programs", "Encrypter")
    if sysinfo["family"] == "macos":
        return os.path.join(os.path.expanduser("~"), "Applications", "Encrypter")
    return os.path.join(os.path.expanduser("~"), ".local", "share", "Encrypter")


def run_logged(cmd, log_q, cwd=None):
    log_q.put("$ " + " ".join(cmd))
    try:
        kwargs = {}
        if sys.platform == "win32":
            kwargs["creationflags"] = subprocess.CREATE_NO_WINDOW
        proc = subprocess.Popen(
            cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, **kwargs,
        )
    except Exception as e:
        log_q.put(f"! failed to start: {e}")
        return 1
    for line in proc.stdout:
        log_q.put(line.rstrip())
    proc.wait()
    return proc.returncode


PY_INSTALL_CMDS = {
    "debian": "sudo apt install -y python3",
    "fedora": "sudo dnf install -y python3",
    "arch": "sudo pacman -S --needed python",
    "gentoo": "sudo emerge --ask dev-lang/python",
    "suse": "sudo zypper install -y python3",
    "alpine": "sudo apk add python3",
}


class InstallerApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Encrypter Setup")
        self.configure(bg=BODY_COLOR)
        self.resizable(False, False)
        self.geometry("560x510")
        apply_dark_titlebar(self)

        header = tk.Frame(self, bg=ACCENT_COLOR, height=84)
        header.pack(fill="x")
        header.pack_propagate(False)
        tk.Label(header, text="Encrypter Setup", bg=ACCENT_COLOR, fg="#ffffff",
                 font=("Segoe UI", 16, "bold")).pack(anchor="w", padx=18, pady=(14, 0))
        tk.Label(header, text="Installs the app, dependencies, and a shortcut.",
                 bg=ACCENT_COLOR, fg=ACCENT_SUBTEXT, font=("Segoe UI", 9)).pack(anchor="w", padx=18)
        tk.Label(header, text=f"Detected system: {SYSTEM_INFO['pretty']}",
                 bg=ACCENT_COLOR, fg=ACCENT_SUBTEXT, font=("Segoe UI", 9, "italic")).pack(anchor="w", padx=18, pady=(2, 0))

        body = tk.Frame(self, bg=BODY_COLOR)
        body.pack(fill="both", expand=True, padx=18, pady=14)

        tk.Label(body, text="Install to:", bg=BODY_COLOR, fg=TEXT_COLOR, font=("Segoe UI", 10)).pack(anchor="w")
        path_row = tk.Frame(body, bg=BODY_COLOR)
        path_row.pack(fill="x", pady=(2, 12))
        self.dir_var = tk.StringVar(value=default_install_dir(SYSTEM_INFO))
        entry = tk.Entry(path_row, textvariable=self.dir_var, bg=EDIT_BG_COLOR, fg=TEXT_COLOR,
                          insertbackground=TEXT_COLOR, relief="flat")
        entry.pack(side="left", fill="x", expand=True, ipady=4)
        tk.Button(path_row, text="Browse...", command=self.browse, bg=BTN_BG, fg=TEXT_COLOR,
                  relief="flat", activebackground=BTN_BG_HOVER, activeforeground=TEXT_COLOR
                  ).pack(side="left", padx=(8, 0))

        self.build_exe_var = tk.BooleanVar(value=False)
        self.shortcut_var = tk.BooleanVar(value=True)
        tk.Checkbutton(body, text="Build a standalone executable (via PyInstaller)",
                        variable=self.build_exe_var, bg=BODY_COLOR, fg=TEXT_COLOR,
                        selectcolor=EDIT_BG_COLOR, activebackground=BODY_COLOR,
                        activeforeground=TEXT_COLOR).pack(anchor="w")
        shortcut_label = {
            "windows": "Create a Desktop shortcut",
            "macos": "Create a Desktop launcher",
            "debian": "Create an application menu entry",
            "fedora": "Create an application menu entry",
            "arch": "Create an application menu entry",
            "gentoo": "Create an application menu entry",
            "suse": "Create an application menu entry",
            "alpine": "Create an application menu entry",
        }.get(SYSTEM_INFO["family"], "Create an application menu entry")
        tk.Checkbutton(body, text=shortcut_label,
                        variable=self.shortcut_var, bg=BODY_COLOR, fg=TEXT_COLOR,
                        selectcolor=EDIT_BG_COLOR, activebackground=BODY_COLOR,
                        activeforeground=TEXT_COLOR).pack(anchor="w", pady=(2, 12))

        self.log = scrolledtext.ScrolledText(body, height=12, bg=EDIT_BG_COLOR, fg=TEXT_COLOR,
                                              insertbackground=TEXT_COLOR, relief="flat", font=("Consolas", 9))
        self.log.pack(fill="both", expand=True)
        self.log.configure(state="disabled")

        btn_row = tk.Frame(self, bg=BODY_COLOR)
        btn_row.pack(fill="x", padx=18, pady=(0, 16))
        self.install_btn = tk.Button(btn_row, text="Install", command=self.start_install, bg=BTN_PRIMARY_BG,
                                      fg="#ffffff", relief="flat", font=("Segoe UI", 10, "bold"), padx=16, pady=6,
                                      activebackground=BTN_PRIMARY_BG_HOVER, activeforeground="#ffffff")
        self.install_btn.pack(side="right")
        tk.Button(btn_row, text="Close", command=self.destroy, bg=BTN_BG, fg=TEXT_COLOR,
                  relief="flat", padx=16, pady=6, activebackground=BTN_BG_HOVER,
                  activeforeground=TEXT_COLOR).pack(side="right", padx=(0, 8))

        self.log_q = queue.Queue()
        self.after(100, self.poll_log)

    def browse(self):
        d = filedialog.askdirectory(initialdir=self.dir_var.get())
        if d:
            self.dir_var.set(d)

    def append_log(self, text):
        self.log.configure(state="normal")
        self.log.insert("end", text + "\n")
        self.log.configure(state="disabled")
        self.log.see("end")

    def poll_log(self):
        try:
            while True:
                line = self.log_q.get_nowait()
                if line == "__ENABLE_BUTTON__":
                    self.install_btn.configure(state="normal")
                else:
                    self.append_log(line)
        except queue.Empty:
            pass
        self.after(100, self.poll_log)

    def start_install(self):
        self.install_btn.configure(state="disabled")
        threading.Thread(target=self.do_install, daemon=True).start()

    def do_install(self):
        q = self.log_q
        target_dir = self.dir_var.get()
        family = SYSTEM_INFO["family"]
        try:
            q.put(f"Detected system: {SYSTEM_INFO['pretty']}")
            os.makedirs(target_dir, exist_ok=True)
            q.put(f"Installing to {target_dir}")

            app_path = os.path.join(target_dir, "encrypter.py")
            with open(app_path, "wb") as f:
                f.write(base64.b64decode(ENCRYPTER_PY_B64))
            q.put("Wrote encrypter.py")

            req_path = os.path.join(target_dir, "requirements.txt")
            with open(req_path, "w", encoding="utf-8") as f:
                f.write(REQUIREMENTS_TXT)
            q.put("Wrote requirements.txt")

            py = find_python()
            if not py:
                q.put("! Python was not found on PATH.")
                if family == "windows":
                    q.put("! Install Python 3.8+ from https://www.python.org/downloads/ and re-run.")
                elif family == "macos":
                    q.put("! Install Python 3.8+ from https://www.python.org/downloads/macos/")
                    q.put("! (or: brew install python) and re-run.")
                elif family in PY_INSTALL_CMDS:
                    q.put(f"! Install it with:  {PY_INSTALL_CMDS[family]}")
                    q.put("! then re-run this installer.")
                else:
                    q.put("! Install Python 3.8+ using your distro's package manager and re-run.")
                return
            q.put(f"Using Python: {py}")

            rc = run_logged([py, "-c", "import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)"], q)
            if rc != 0:
                q.put("! Python 3.8+ is required.")
                return

            rc = run_logged([py, "-c", "import tkinter"], q)
            if rc != 0:
                q.put("! tkinter is missing from this Python install.")
                if family == "windows":
                    q.put('! Reinstall Python with "tcl/tk and IDLE" checked.')
                elif SYSTEM_INFO.get("pkg_cmd"):
                    q.put(f"! Install it with:  {SYSTEM_INFO['pkg_cmd']}")
                else:
                    q.put("! Install the Tk/tkinter package for your distro (often 'python3-tk' or 'tk').")
                return

            with open(req_path, "r", encoding="utf-8") as f:
                real_reqs = [l for l in f if l.strip() and not l.strip().startswith("#")]
            if real_reqs:
                q.put("Installing dependencies from requirements.txt (cryptography, etc.) ...")
                run_logged([py, "-m", "pip", "install", "-r", req_path], q)
            else:
                q.put("No extra packages required.")

            exe_path = None
            if self.build_exe_var.get():
                q.put("Installing PyInstaller ...")
                run_logged([py, "-m", "pip", "install", "--upgrade", "pyinstaller"], q)
                q.put("Building the Encrypter executable (this can take a minute) ...")
                dist_dir = os.path.join(target_dir, "dist")
                build_dir = os.path.join(target_dir, "build")
                cmd = [py, "-m", "PyInstaller", "--onefile", "--name", "Encrypter",
                       "--distpath", dist_dir, "--workpath", build_dir, "--specpath", build_dir]
                if family in ("windows", "macos"):
                    cmd.append("--noconsole")
                cmd.append(app_path)
                run_logged(cmd, q)
                candidate = os.path.join(dist_dir, "Encrypter.exe" if family == "windows" else "Encrypter")
                if os.path.exists(candidate):
                    exe_path = candidate
                    q.put(f"Built: {exe_path}")
                else:
                    q.put("! Build did not produce an executable -- see log above.")

            if self.shortcut_var.get():
                if family == "windows":
                    ps1_path = os.path.join(target_dir, "create_shortcut.ps1")
                    with open(ps1_path, "w", encoding="utf-8") as f:
                        f.write(CREATE_SHORTCUT_PS1)
                    if exe_path:
                        cmd = ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", ps1_path,
                               "-Target", exe_path, "-WorkingDirectory", target_dir]
                    else:
                        pyw = shutil.which("pythonw") or py
                        cmd = ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", ps1_path,
                               "-Target", pyw, "-Arguments", app_path, "-WorkingDirectory", target_dir]
                    run_logged(cmd, q)

                elif family == "macos":
                    exec_cmd = f'"{exe_path}"' if exe_path else f'"{py}" "{app_path}"'
                    launcher = MACOS_LAUNCHER_COMMAND.format(workdir=target_dir, exec_cmd=exec_cmd)
                    desktop_path = os.path.join(os.path.expanduser("~"), "Desktop", "Encrypter.command")
                    try:
                        with open(desktop_path, "w", encoding="utf-8") as f:
                            f.write(launcher)
                        os.chmod(desktop_path, 0o755)
                        q.put(f"Created launcher: {desktop_path}")
                        q.put("Note: the first time you double-click it, macOS Gatekeeper may require")
                        q.put("right-click -> Open once, since it isn't a signed/notarized app.")
                    except OSError as e:
                        q.put(f"! Could not create Desktop launcher: {e}")

                else:  # Linux and other Unix-like systems
                    exec_cmd = f'"{exe_path}"' if exe_path else f'"{py}" "{app_path}"'
                    entry = LINUX_DESKTOP_ENTRY.format(workdir=target_dir, exec_cmd=exec_cmd)
                    apps_dir = os.path.join(os.path.expanduser("~"), ".local", "share", "applications")
                    try:
                        os.makedirs(apps_dir, exist_ok=True)
                        entry_path = os.path.join(apps_dir, "encrypter.desktop")
                        with open(entry_path, "w", encoding="utf-8") as f:
                            f.write(entry)
                        os.chmod(entry_path, 0o755)
                        q.put(f"Created application menu entry: {entry_path}")
                    except OSError as e:
                        q.put(f"! Could not create application menu entry: {e}")

                    desktop_dir = os.path.join(os.path.expanduser("~"), "Desktop")
                    if os.path.isdir(desktop_dir):
                        try:
                            desktop_copy = os.path.join(desktop_dir, "Encrypter.desktop")
                            with open(desktop_copy, "w", encoding="utf-8") as f:
                                f.write(entry)
                            os.chmod(desktop_copy, 0o755)
                            q.put(f"Created Desktop shortcut: {desktop_copy}")
                            q.put("Note: some desktop environments require right-click -> 'Allow Launching'")
                            q.put("the first time you use a new .desktop file.")
                        except OSError as e:
                            q.put(f"! Could not create Desktop shortcut: {e}")

            q.put("")
            q.put("Done.")
            if exe_path:
                q.put(f"Run: {exe_path}")
            else:
                q.put(f'Run: {py} "{app_path}"')
        except Exception as e:
            q.put(f"! Unexpected error: {e}")
        finally:
            q.put("__ENABLE_BUTTON__")


if __name__ == "__main__":
    InstallerApp().mainloop()
